/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_sp00kyprocessor_free: (a: number, b: number) => void;
export const init: () => void;
export const sp00kyprocessor_compact: (a: number) => number;
export const sp00kyprocessor_dead_bytes: (a: number) => number;
export const sp00kyprocessor_ingest: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any) => [number, number, number];
export const sp00kyprocessor_ingest_many: (a: number, b: any) => [number, number, number];
export const sp00kyprocessor_live_bytes: (a: number) => number;
export const sp00kyprocessor_load_state: (a: number, b: number, c: number) => [number, number];
export const sp00kyprocessor_load_store_state: (a: number, b: number, c: number) => [number, number, number];
export const sp00kyprocessor_max_row_versions: (a: number) => [number, number, number];
export const sp00kyprocessor_new: () => number;
export const sp00kyprocessor_reconcile: (a: number, b: number, c: number, d: any) => [number, number, number];
export const sp00kyprocessor_register_view: (a: number, b: any) => [number, number, number];
export const sp00kyprocessor_save_state: (a: number) => [number, number, number, number];
export const sp00kyprocessor_save_store_state: (a: number) => [number, number, number, number];
export const sp00kyprocessor_set_permissions: (a: number, b: any) => [number, number];
export const sp00kyprocessor_set_projection: (a: number, b: number) => void;
export const sp00kyprocessor_size_report: (a: number) => [number, number, number];
export const sp00kyprocessor_unregister_view: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
