// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'client.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_db`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SurrealDb>>
abstract class SurrealDb implements RustOpaqueInterface {
  Future<void> authenticate({required String token});

  Future<void> close();

  static Future<SurrealDb> connect({required StorageMode mode}) =>
      RustLib.instance.api.crateApiClientSurrealDbConnect(mode: mode);

  Future<String> create({required String resource, String? data});

  Future<String> delete({required String resource});

  Future<void> export_({required String path});

  Future<void> invalidate();

  Future<String> merge({required String resource, String? data});

  /// Execute a raw SQL query.
  /// `vars` should be a JSON string of bind variables, e.g. `{"id": "...", "val": 123}`.
  /// Execute a raw SQL query.
  /// `vars` should be a JSON string of bind variables, e.g. `{"id": "...", "val": 123}`.
  Future<String> query({required String sql, String? vars});

  Future<void> queryBegin();

  Future<void> queryCancel();

  Future<void> queryCommit();

  Future<String> select({required String resource});

  Future<String> signin({required String credentialsJson});

  Future<String> signup({required String credentialsJson});

  Future<String> transaction({required String statements, String? vars});

  Future<String> update({required String resource, String? data});

  Future<void> useDb({required String namespace, required String database});
}

@freezed
sealed class StorageMode with _$StorageMode {
  const StorageMode._();

  const factory StorageMode.memory() = StorageMode_Memory;
  const factory StorageMode.disk({required String path}) = StorageMode_Disk;
  const factory StorageMode.remote({required String url}) = StorageMode_Remote;
}
