import React, { useState } from 'react';

type HoverId = 'user-table' | 'user-username' | 'thread-table' | 'thread-title' | 'thread-author' | 'relationships' | null;

export default function SchemaGenerator() {
  const [hoveredId, setHoveredId] = useState<HoverId>(null);

  const getOpacityClass = (id: HoverId) => {
    if (!hoveredId) return 'opacity-100';
    return hoveredId === id ? 'opacity-100 bg-white/5 shadow-[0_0_15px_rgba(255,255,255,0.1)]' : 'opacity-30 blur-[1px]';
  };

  const InputLine = ({ id, children }: { id: HoverId; children: React.ReactNode }) => (
    <div
      onMouseEnter={() => setHoveredId(id)}
      onMouseLeave={() => setHoveredId(null)}
      className={`cursor-crosshair transition-all duration-300 rounded px-2 -mx-2 hover:bg-white/10 ${
        hoveredId && hoveredId !== id ? 'opacity-30' : 'opacity-100'
      }`}
    >
      {children}
    </div>
  );

  return (
    <div className="border border-[#333] bg-[#050505] rounded-sm overflow-hidden shadow-2xl flex flex-col h-full">
      <div className="bg-[#111] border-b border-[#222] px-4 py-2 flex items-center justify-between">
        <div className="flex gap-2">
          <div className="w-3 h-3 rounded-full bg-[#333]"></div>
          <div className="w-3 h-3 rounded-full bg-[#333]"></div>
        </div>
        <div className="flex text-xs font-mono text-gray-500 gap-6">
          <span className="text-white border-b border-white pb-0.5">Split View</span>
          <span>100%</span>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 h-full font-mono text-sm relative">
        {/* INPUT SECTION */}
        <div className="p-6 border-r border-[#222] relative group">
          <div className="absolute top-0 right-0 bg-green-900/20 text-xs text-green-500 px-2 py-1 border-b border-l border-green-900/30 font-bold">
            INPUT
          </div>
          <div className="text-gray-400 leading-relaxed">
            <InputLine id="user-table">
              <p>
                <span className="text-purple-400">DEFINE TABLE</span> user <span className="text-purple-400">SCHEMAFULL</span>;
              </p>
            </InputLine>
            <InputLine id="user-username">
              <p className="mb-4">
                <span className="text-purple-400">DEFINE FIELD</span> username <span className="text-purple-400">ON</span> user <span className="text-blue-400">TYPE string</span>;
              </p>
            </InputLine>

            <InputLine id="thread-table">
              <p>
                <span className="text-purple-400">DEFINE TABLE</span> thread <span className="text-purple-400">SCHEMAFULL</span>;
              </p>
            </InputLine>
            <InputLine id="thread-title">
              <p>
                <span className="text-purple-400">DEFINE FIELD</span> title <span className="text-purple-400">ON</span> thread <span className="text-blue-400">TYPE string</span>;
              </p>
            </InputLine>
            <InputLine id="thread-author">
              <div className="relative">
                <p>
                  <span className="text-purple-400">DEFINE FIELD</span> author <span className="text-purple-400">ON</span> thread <span className="text-blue-400">TYPE record&lt;user&gt;</span>;
                </p>
              </div>
            </InputLine>
          </div>
        </div>

        {/* MIDDLE ARROW */}
        <div className="hidden md:flex absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 bg-[#222] border border-[#444] rounded-full items-center justify-center z-10 text-green-500 shadow-xl pointer-events-none">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth="2"
            stroke="currentColor"
            className="w-4 h-4"
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3"></path>
          </svg>
        </div>

        {/* GENERATED OUTPUT SECTION */}
        <div className="p-6 bg-[#0a0a0a] relative">
          <div className="absolute top-0 right-0 bg-purple-900/20 text-xs text-purple-400 px-2 py-1 border-b border-l border-purple-900/30 font-bold">
            GENERATED
          </div>
          <div className="text-gray-400 leading-relaxed font-mono text-[10px] md:text-sm overflow-x-auto whitespace-nowrap scrollbar-hide">
            <p className="text-gray-600 mb-2">// @generated by spooky-cli</p>

            <p>
              <span className="text-purple-400">export const</span> <span className="text-yellow-200">schema</span> = &#123;
            </p>
            <p className="pl-4">
              <span className="text-blue-300">tables</span>: [
            </p>

            {/* USER TABLE */}
            {/* USER TABLE */}
            <div>
              <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('user-table')}`}>
                <p className="pl-8">&#123;</p>
                <p className="pl-12">
                  <span className="text-blue-300">name</span>: <span className="text-green-300">'user'</span> <span className="text-purple-400">as const</span>,
                </p>
                <p className="pl-12">
                  <span className="text-blue-300">columns</span>: &#123;
                </p>
                <p className="pl-16">
                  <span className="text-blue-300">id</span>: &#123; <span className="text-blue-300">type</span>: <span className="text-green-300">'string'</span> <span className="text-purple-400">as const</span>, <span className="text-blue-300">recordId</span>: <span className="text-orange-400">true</span>, <span className="text-blue-300">optional</span>: <span className="text-orange-400">false</span> &#125;,
                </p>
              </div>

              <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('user-username')}`}>
                <p className="pl-16">
                  <span className="text-blue-300">username</span>: &#123; <span className="text-blue-300">type</span>: <span className="text-green-300">'string'</span> <span className="text-purple-400">as const</span>, <span className="text-blue-300">optional</span>: <span className="text-orange-400">false</span> &#125;,
                </p>
              </div>

              <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('user-table')}`}>
                 <p className="pl-12">&#125;,</p>
                 <div className="relative">
                  <p className="pl-12">
                     <span className="text-blue-300">primaryKey</span>: [<span className="text-green-300">'id'</span>] <span className="text-purple-400">as const</span>,
                  </p>
                 </div>
                 <p className="pl-8">&#125;,</p>
              </div>
            </div>

             {/* THREAD TABLE */}
             {/* THREAD TABLE */}
             <div>
              <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('thread-table')}`}>
                <p className="pl-8">&#123;</p>
                <p className="pl-12">
                  <span className="text-blue-300">name</span>: <span className="text-green-300">'thread'</span> <span className="text-purple-400">as const</span>,
                </p>
                <p className="pl-12">
                  <span className="text-blue-300">columns</span>: &#123;
                </p>
                 <p className="pl-16">
                  <span className="text-blue-300">id</span>: &#123; <span className="text-blue-300">type</span>: <span className="text-green-300">'string'</span> <span className="text-purple-400">as const</span>, <span className="text-blue-300">recordId</span>: <span className="text-orange-400">true</span>, <span className="text-blue-300">optional</span>: <span className="text-orange-400">false</span> &#125;,
                </p>
              </div>

               <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('thread-title')}`}>
                <p className="pl-16">
                  <span className="text-blue-300">title</span>: &#123; <span className="text-blue-300">type</span>: <span className="text-green-300">'string'</span> <span className="text-purple-400">as const</span>, <span className="text-blue-300">optional</span>: <span className="text-orange-400">false</span> &#125;,
                </p>
              </div>

              <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('thread-author')}`}>
                <p className="pl-16">
                  <span className="text-blue-300">author</span>: &#123; <span className="text-blue-300">type</span>: <span className="text-green-300">'string'</span> <span className="text-purple-400">as const</span>, <span className="text-blue-300">recordId</span>: <span className="text-orange-400">true</span>, <span className="text-blue-300">optional</span>: <span className="text-orange-400">false</span> &#125;,
                </p>
              </div>

               <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('thread-table')}`}>
                 <p className="pl-12">&#125;,</p>
                 <div className="relative">
                  <p className="pl-12">
                    <span className="text-blue-300">primaryKey</span>: [<span className="text-green-300">'id'</span>] <span className="text-purple-400">as const</span>,
                  </p>
                </div>
                 <p className="pl-8">&#125;,</p>
              </div>
            </div>
            
             <p className="pl-4">],</p>


            {/* RELATIONSHIPS */}
            <div className={`transition-all duration-300 rounded px-2 -mx-2 ${getOpacityClass('thread-author')}`}>
               <p className="pl-4">
                  <span className="text-blue-300">relationships</span>: [
                </p>
                <p className="pl-8">&#123;</p>
                <p className="pl-12">
                  <span className="text-blue-300">from</span>: <span className="text-green-300">'thread'</span> <span className="text-purple-400">as const</span>,
                </p>
                <p className="pl-12">
                  <span className="text-blue-300">field</span>: <span className="text-green-300">'author'</span> <span className="text-purple-400">as const</span>,
                </p>
                <p className="pl-12">
                  <span className="text-blue-300">to</span>: <span className="text-green-300">'user'</span> <span className="text-purple-400">as const</span>,
                </p>
                <p className="pl-12">
                  <span className="text-blue-300">cardinality</span>: <span className="text-green-300">'one'</span> <span className="text-purple-400">as const</span>
                </p>
                <p className="pl-8">&#125;,</p>
                <p className="pl-8 text-gray-600">...</p>
                <p className="pl-4">]</p>
            </div>
           
            <p>&#125;;</p>
          </div>
        </div>
      </div>
    </div>
  );
}
