import React, { useState, useRef, useEffect } from 'react';

type LayerKey = 'editor' | 'types' | 'schema';

const LAYERS: {
  key: LayerKey;
  label: string;
  sublabel: string;
  accent: string;
  accentBorder: string;
}[] = [
  {
    key: 'schema',
    label: 'Schema',
    sublabel: 'schema.surql',
    accent: '#34d399',
    accentBorder: 'rgba(52,211,153,0.5)',
  },
  {
    key: 'types',
    label: 'Types',
    sublabel: 'schema.generated.ts',
    accent: '#38bdf8',
    accentBorder: 'rgba(56,189,248,0.5)',
  },
  {
    key: 'editor',
    label: 'Editor',
    sublabel: 'ThreadList.tsx',
    accent: '#a78bfa',
    accentBorder: 'rgba(167,139,250,0.5)',
  },
];

type CodeLine = { tokens: { text: string; c: string }[] };

const editorCode: CodeLine[] = [
  { tokens: [{ text: 'import', c: '#c084fc' }, { text: ' { useQuery } ', c: '#cbd5e1' }, { text: 'from', c: '#c084fc' }, { text: ' ', c: '#cbd5e1' }, { text: '"spooky/solid"', c: '#fdba74' }] },
  { tokens: [{ text: 'import', c: '#c084fc' }, { text: ' { db } ', c: '#cbd5e1' }, { text: 'from', c: '#c084fc' }, { text: ' ', c: '#cbd5e1' }, { text: '"./client"', c: '#fdba74' }] },
  { tokens: [{ text: '', c: '#64748b' }] },
  { tokens: [{ text: 'export default function', c: '#c084fc' }, { text: ' ThreadList() {', c: '#cbd5e1' }] },
  { tokens: [{ text: '  const', c: '#c084fc' }, { text: ' threads = ', c: '#cbd5e1' }, { text: 'useQuery', c: '#60a5fa' }, { text: '(', c: '#64748b' }] },
  { tokens: [{ text: '    db', c: '#60a5fa' }, { text: '.', c: '#64748b' }, { text: 'query', c: '#60a5fa' }, { text: '(', c: '#64748b' }, { text: '"thread"', c: '#fdba74' }, { text: ')', c: '#64748b' }] },
  { tokens: [{ text: '      .', c: '#64748b' }, { text: 'related', c: '#60a5fa' }, { text: '(', c: '#64748b' }, { text: '"comments"', c: '#fdba74' }, { text: ')', c: '#64748b' }] },
  { tokens: [{ text: '      .', c: '#64748b' }, { text: 'orderBy', c: '#60a5fa' }, { text: '(', c: '#64748b' }, { text: '"created_at"', c: '#fdba74' }, { text: ', ', c: '#64748b' }, { text: '"desc"', c: '#fdba74' }, { text: ')', c: '#64748b' }] },
  { tokens: [{ text: '      .', c: '#64748b' }, { text: 'build', c: '#60a5fa' }, { text: '()', c: '#64748b' }] },
  { tokens: [{ text: '  )', c: '#64748b' }] },
];

const typesCode: CodeLine[] = [
  { tokens: [{ text: '// @generated by spooky-cli', c: '#546e7a' }] },
  { tokens: [{ text: 'export type', c: '#c084fc' }, { text: ' Thread = {', c: '#cbd5e1' }] },
  { tokens: [{ text: '  id', c: '#cbd5e1' }, { text: ': ', c: '#64748b' }, { text: 'string', c: '#38bdf8' }] },
  { tokens: [{ text: '  title', c: '#cbd5e1' }, { text: ': ', c: '#64748b' }, { text: 'string', c: '#38bdf8' }] },
  { tokens: [{ text: '  body', c: '#cbd5e1' }, { text: ': ', c: '#64748b' }, { text: 'string', c: '#38bdf8' }] },
  { tokens: [{ text: '  author', c: '#cbd5e1' }, { text: ': ', c: '#64748b' }, { text: 'Record', c: '#38bdf8' }, { text: '<', c: '#64748b' }, { text: 'User', c: '#38bdf8' }, { text: '>', c: '#64748b' }] },
  { tokens: [{ text: '  comments', c: '#cbd5e1' }, { text: ': ', c: '#64748b' }, { text: 'Comment', c: '#38bdf8' }, { text: '[]', c: '#64748b' }] },
  { tokens: [{ text: '  created_at', c: '#cbd5e1' }, { text: ': ', c: '#64748b' }, { text: 'Date', c: '#38bdf8' }] },
  { tokens: [{ text: '}', c: '#cbd5e1' }] },
];

const schemaCode: CodeLine[] = [
  { tokens: [{ text: 'DEFINE TABLE', c: '#c084fc' }, { text: ' thread ', c: '#cbd5e1' }, { text: 'SCHEMAFULL', c: '#c084fc' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE FIELD', c: '#c084fc' }, { text: ' title ', c: '#cbd5e1' }, { text: 'ON', c: '#c084fc' }, { text: ' thread ', c: '#cbd5e1' }, { text: 'TYPE', c: '#c084fc' }, { text: ' string', c: '#34d399' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE FIELD', c: '#c084fc' }, { text: ' body ', c: '#cbd5e1' }, { text: 'ON', c: '#c084fc' }, { text: ' thread ', c: '#cbd5e1' }, { text: 'TYPE', c: '#c084fc' }, { text: ' string', c: '#34d399' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE FIELD', c: '#c084fc' }, { text: ' author ', c: '#cbd5e1' }, { text: 'ON', c: '#c084fc' }, { text: ' thread ', c: '#cbd5e1' }, { text: 'TYPE', c: '#c084fc' }, { text: ' record', c: '#34d399' }, { text: '<user>', c: '#34d399' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE FIELD', c: '#c084fc' }, { text: ' created_at ', c: '#cbd5e1' }, { text: 'ON', c: '#c084fc' }, { text: ' thread ', c: '#cbd5e1' }, { text: 'TYPE', c: '#c084fc' }, { text: ' datetime', c: '#34d399' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: '', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE TABLE', c: '#c084fc' }, { text: ' user ', c: '#cbd5e1' }, { text: 'SCHEMAFULL', c: '#c084fc' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE FIELD', c: '#c084fc' }, { text: ' username ', c: '#cbd5e1' }, { text: 'ON', c: '#c084fc' }, { text: ' user ', c: '#cbd5e1' }, { text: 'TYPE', c: '#c084fc' }, { text: ' string', c: '#34d399' }, { text: ';', c: '#64748b' }] },
  { tokens: [{ text: 'DEFINE FIELD', c: '#c084fc' }, { text: ' email ', c: '#cbd5e1' }, { text: 'ON', c: '#c084fc' }, { text: ' user ', c: '#cbd5e1' }, { text: 'TYPE', c: '#c084fc' }, { text: ' string', c: '#34d399' }, { text: ';', c: '#64748b' }] },
];

const CODE_MAP: Record<LayerKey, CodeLine[]> = {
  editor: editorCode,
  types: typesCode,
  schema: schemaCode,
};

const LAYER_W = 320;
const LAYER_GAP_Z = 90;

function FlatIsometricLayer({
  layer,
  index,
  hovered,
  onHover,
}: {
  layer: (typeof LAYERS)[number];
  index: number;
  hovered: LayerKey | null;
  onHover: (key: LayerKey | null) => void;
}) {
  const isHovered = hovered === layer.key;
  const isDimmed = hovered !== null && !isHovered;
  const liftZ = isHovered ? 16 : 0;
  const zOffset = index * LAYER_GAP_Z + liftZ;

  const lines = CODE_MAP[layer.key];

  // Counter-rotate to make the layer readable when hovered
  const counterTransform = isHovered
    ? `translateX(-50%) translateZ(${zOffset}px) rotateZ(45deg) rotateX(-55deg) scale(1.15)`
    : `translateX(-50%) translateZ(${zOffset}px)`;

  return (
    <div
      style={{
        position: 'absolute',
        bottom: 0,
        left: '50%',
        transform: counterTransform,
        opacity: isDimmed ? 0 : 1,
        filter: isDimmed ? 'brightness(0.5)' : 'brightness(1)',
        transition: 'all 500ms cubic-bezier(0.4, 0, 0.2, 1)',
        pointerEvents: 'none' as const,
        zIndex: isHovered ? 10 : index,
      }}
    >
      <div
        style={{
          width: LAYER_W,
          background: '#111113',
          border: `1px solid ${isHovered ? layer.accentBorder : 'rgba(255,255,255,0.08)'}`,
          borderRadius: 10,
          transition: 'all 500ms cubic-bezier(0.4, 0, 0.2, 1)',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: isHovered
            ? `0 0 40px ${layer.accent}15, 0 8px 30px rgba(0,0,0,0.5)`
            : '0 4px 16px rgba(0,0,0,0.4)',
        }}
      >
        {/* Window titlebar */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            padding: '8px 12px',
            background: '#0a0a0c',
            borderBottom: `1px solid ${isHovered ? layer.accentBorder : 'rgba(255,255,255,0.06)'}`,
            borderRadius: '10px 10px 0 0',
            transition: 'all 300ms ease',
          }}
        >
          {/* Traffic lights */}
          <div style={{ display: 'flex', gap: 4 }}>
            <div style={{ width: 6, height: 6, borderRadius: '50%', background: 'rgba(255,255,255,0.08)' }} />
            <div style={{ width: 6, height: 6, borderRadius: '50%', background: 'rgba(255,255,255,0.08)' }} />
            <div style={{ width: 6, height: 6, borderRadius: '50%', background: 'rgba(255,255,255,0.08)' }} />
          </div>
          <span
            style={{
              fontFamily: "'JetBrains Mono', monospace",
              fontSize: 9,
              fontWeight: 500,
              color: isHovered ? layer.accent : 'rgba(255,255,255,0.3)',
              letterSpacing: '0.02em',
              transition: 'color 300ms ease',
            }}
          >
            {layer.sublabel}
          </span>
        </div>

        {/* Code body */}
        <div style={{ padding: '10px 16px 12px' }}>
          {lines.map((line, i) => (
            <div
              key={i}
              style={{
                fontFamily: "'JetBrains Mono', monospace",
                fontSize: 10,
                lineHeight: '17px',
                whiteSpace: 'nowrap',
              }}
            >
              {line.tokens.map((t, j) => (
                <span key={j} style={{ color: t.c }}>{t.text}</span>
              ))}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ─── Mobile: scroll-driven crossfade ─── */
function MobileLayerCard({ layer, active }: { layer: (typeof LAYERS)[number]; active: boolean }) {
  const lines = CODE_MAP[layer.key];
  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        opacity: active ? 1 : 0,
        transition: 'opacity 0.5s ease',
        pointerEvents: active ? 'auto' : 'none',
        padding: '0 12px',
      }}
    >
      <div
        style={{
          background: '#111113',
          border: `1px solid ${active ? layer.accentBorder : 'rgba(255,255,255,0.08)'}`,
          borderRadius: 12,
          transition: 'border-color 0.3s ease',
          boxShadow: active ? `0 0 30px ${layer.accent}12, 0 4px 20px rgba(0,0,0,0.4)` : 'none',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 8,
            padding: '8px 12px',
            background: '#0a0a0c',
            borderBottom: '1px solid rgba(255,255,255,0.06)',
            borderRadius: '12px 12px 0 0',
          }}
        >
          <div style={{ display: 'flex', gap: 5 }}>
            <div style={{ width: 7, height: 7, borderRadius: '50%', background: 'rgba(255,255,255,0.1)' }} />
            <div style={{ width: 7, height: 7, borderRadius: '50%', background: 'rgba(255,255,255,0.1)' }} />
            <div style={{ width: 7, height: 7, borderRadius: '50%', background: 'rgba(255,255,255,0.1)' }} />
          </div>
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, fontWeight: 500, color: layer.accent }}>
            {layer.sublabel}
          </span>
        </div>
        <div style={{ padding: '8px 14px 10px', overflowX: 'auto' }}>
          {lines.map((line, i) => (
            <div key={i} style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10.5, lineHeight: '17px', whiteSpace: 'nowrap' }}>
              {line.tokens.map((t, j) => (
                <span key={j} style={{ color: t.c }}>{t.text}</span>
              ))}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function MobileLayerCrossfade() {
  const layers = [...LAYERS].reverse();
  const containerRef = useRef<HTMLDivElement>(null);
  const [activeIndex, setActiveIndex] = useState(0);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const handleScroll = () => {
      const rect = container.getBoundingClientRect();
      const viewportH = window.innerHeight;
      const raw = Math.max(0, Math.min(1, (viewportH - rect.top) / (viewportH + rect.height)));
      const clamped = Math.max(0, Math.min(1, (raw - 0.25) / 0.5));
      const index = Math.min(layers.length - 1, Math.floor(clamped * layers.length));
      setActiveIndex(index);
      setProgress(clamped);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    handleScroll();
    return () => window.removeEventListener('scroll', handleScroll);
  }, [layers.length]);

  return (
    <div ref={containerRef} style={{ position: 'relative', width: '100%', height: 200 }}>
      {layers.map((layer, i) => (
        <MobileLayerCard key={layer.key} layer={layer} active={activeIndex === i} />
      ))}
      {/* Bottom bar: progress + dots */}
      <div style={{ position: 'absolute', bottom: -24, left: 12, right: 12, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
        {/* Scroll progress bar */}
        <div style={{ width: '100%', height: 2, background: 'rgba(255,255,255,0.06)', borderRadius: 1, overflow: 'hidden' }}>
          <div
            style={{
              height: '100%',
              width: `${progress * 100}%`,
              background: layers[activeIndex].accent,
              borderRadius: 1,
              transition: 'background 0.3s ease',
            }}
          />
        </div>
        {/* Dots */}
        <div style={{ display: 'flex', justifyContent: 'center', gap: 6 }}>
          {layers.map((layer, i) => (
            <div
              key={layer.key}
              style={{
                width: activeIndex === i ? 16 : 6,
                height: 6,
                borderRadius: 3,
                background: activeIndex === i ? layer.accent : 'rgba(255,255,255,0.15)',
                transition: 'all 0.3s ease',
              }}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

export const SchemaLayerStack: React.FC = () => {
  const [hovered, setHovered] = useState<LayerKey | null>(null);

  const sceneHeight = 480;

  return (
    <div style={{ width: '100%' }}>
      {/* Desktop: isometric flat windows in 3D space */}
      <div
        className="hidden md:flex"
        style={{
          justifyContent: 'center',
          alignItems: 'center',
          position: 'relative',
          minHeight: sceneHeight,
        }}
      >
        {/* Isometric scene */}
        <div
          style={{
            position: 'relative',
            width: LAYER_W + 80,
            height: sceneHeight,
            perspective: 1000,
            marginLeft: -60,
          }}
        >
          <div
            style={{
              position: 'relative',
              width: '100%',
              height: '100%',
              transformStyle: 'preserve-3d',
              transform: 'rotateX(55deg) rotateZ(-45deg)',
            }}
          >
            {LAYERS.map((layer, i) => (
              <FlatIsometricLayer
                key={layer.key}
                layer={layer}
                index={i}
                hovered={hovered}
                onHover={setHovered}
              />
            ))}
          </div>
        </div>

        {/* Layer labels on the left */}
        <div
          style={{
            position: 'absolute',
            left: 12,
            top: 0,
            bottom: 0,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            paddingTop: 30,
            paddingBottom: 90,
            pointerEvents: 'auto',
          }}
        >
          {[...LAYERS].reverse().map((layer) => {
            const isActive = hovered === layer.key;
            return (
              <div
                key={layer.key}
                onMouseEnter={() => setHovered(layer.key)}
                onMouseLeave={() => setHovered(null)}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 10,
                  opacity: hovered === null ? 1 : isActive ? 1 : 0,
                  transition: 'all 300ms cubic-bezier(0.4, 0, 0.2, 1)',
                  cursor: 'pointer',
                }}
              >
                <span
                  style={{
                    fontSize: 10,
                    fontWeight: 600,
                    color: isActive ? layer.accent : 'rgba(255,255,255,0.5)',
                    letterSpacing: '0.08em',
                    textTransform: 'uppercase',
                    fontFamily: "'JetBrains Mono', monospace",
                    transition: 'color 300ms ease',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {layer.label}
                </span>
                <div
                  style={{
                    width: 32,
                    height: 1,
                    background: isActive
                      ? `linear-gradient(90deg, ${layer.accent}, transparent)`
                      : 'rgba(255,255,255,0.15)',
                    transition: 'background 300ms ease',
                  }}
                />
              </div>
            );
          })}
        </div>
      </div>

      {/* Mobile: scroll-driven crossfade */}
      <div className="block md:hidden">
        <MobileLayerCrossfade />
      </div>
    </div>
  );
};
