// GENERATED FILE - do not edit.
// Generated by tool/gen_maps.dart

library schema.models_maps;

/// Helper that builds a JSON-like map for `Comment`
Map<String, dynamic> commentMap({
  required String author,
  required String content,
  DateTime? createdAt,
  required String id,
  required String thread,
}) {
  return {
    'author': author,
    'content': content,
    'created_at': createdAt?.toIso8601String(),
    'id': id,
    'thread': thread,
  };
}

/// Helper that builds a JSON-like map for `CommentedOn`
Map<String, dynamic> commentedOnMap({required String id}) {
  return {'id': id};
}

/// Helper that builds a JSON-like map for `Thread`
Map<String, dynamic> threadMap({
  required String author,
  List<String>? comments,
  required String content,
  DateTime? createdAt,
  required String id,
  required String title,
}) {
  return {
    'author': author,
    'comments': comments == null
        ? []
        : List<dynamic>.from(comments.map((x) => x)),
    'content': content,
    'created_at': createdAt?.toIso8601String(),
    'id': id,
    'title': title,
  };
}

/// Helper that builds a JSON-like map for `User`
Map<String, dynamic> userMap({
  List<String>? comments,
  required String id,
  List<String>? threads,
  required String username,
}) {
  return {
    'comments': comments == null
        ? []
        : List<dynamic>.from(comments.map((x) => x)),
    'id': id,
    'threads': threads == null ? [] : List<dynamic>.from(threads.map((x) => x)),
    'username': username,
  };
}
