// ⚠️  WARNING: This file is automatically generated by syncgen.
// Do not modify this file manually as changes will be overwritten.
// To regenerate this file, run the syncgen command from the database package.
// Generated on: 2025-10-17 19:36:49 UTC

export interface TempSchema {
  comment: Comment;
  thread: Thread;
  user: User;
  [key: string]: any;
}

export interface Comment {
  /**
   * Record ID of table: user
   */
  author?: string;
  /**
   * Assert: $value != NONE AND string::len($value) > 0
   */
  content: string;
  created_at?: Date;
  /**
   * Record ID
   */
  id: string;
  /**
   * Record ID of table: thread
   */
  thread_id: string;
}

export interface Thread {
  /**
   * Record ID of table: user
   */
  author?: string;
  /**
   * Assert: $value != NONE AND string::len($value) > 0
   */
  content: string;
  created_at?: Date;
  /**
   * Record ID
   */
  id: string;
  /**
   * Assert: $value != NONE AND string::len($value) > 0 AND string::len($value) <= 200
   */
  title: string;
}

export interface User {
  created_at?: Date;
  /**
   * Record ID
   */
  id: string;
  /**
   * Assert: $value != NONE AND string::len($value) > 0
   */
  password: string;
  /**
   * Assert: $value != NONE AND string::is::alphanum($value) AND string::len($value) > 3
   */
  username: string;
}
