// ⚠️  WARNING: This file is automatically generated by syncgen.
// Do not modify this file manually as changes will be overwritten.
// To regenerate this file, run the syncgen command from the database package.
// Generated on: 2025-10-14 14:41:07 UTC

export interface TempSchema {
    friend_request?: FriendRequest;
    message?:        Message;
    user?:           User;
    [property: string]: any;
}

export interface FriendRequest {
    created_at?: Date;
    /**
     * Record ID of table: user
     */
    from?: string;
    /**
     * Record ID
     */
    id: string;
    /**
     * Assert: $value INSIDE ['pending', 'accepted', 'rejected']
     */
    status?: string;
    /**
     * Record ID of table: user
     */
    to: string;
}

export interface Message {
    /**
     * Assert: $value != NONE AND string::len($value) > 0
     */
    content: string;
    /**
     * Record ID of table: user
     */
    from?: string;
    /**
     * Record ID
     */
    id:       string;
    read_at?: Date | null;
    sent_at?: Date;
    /**
     * Record ID of table: user
     */
    to: string;
}

export interface User {
    created_at?: Date;
    /**
     * Assert: string::is::email($value)
     */
    email:   string;
    friends: string[];
    /**
     * Record ID
     */
    id: string;
    /**
     * Assert: $value != NONE AND string::is::alphanum($value) AND string::len($value) > 3
     */
    username: string;
}
