// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1953876643;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_surrealdb',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiClientSurrealDbAuthenticate({
    required SurrealDb that,
    required String token,
  });

  Future<void> crateApiClientSurrealDbClose({required SurrealDb that});

  Future<SurrealDb> crateApiClientSurrealDbConnect({required StorageMode mode});

  Future<String> crateApiClientSurrealDbCreate({
    required SurrealDb that,
    required String resource,
    String? data,
  });

  Future<String> crateApiClientSurrealDbDelete({
    required SurrealDb that,
    required String resource,
  });

  Future<void> crateApiClientSurrealDbExport({
    required SurrealDb that,
    required String path,
  });

  Future<void> crateApiClientSurrealDbInvalidate({required SurrealDb that});

  Future<String> crateApiClientSurrealDbMerge({
    required SurrealDb that,
    required String resource,
    String? data,
  });

  Future<String> crateApiClientSurrealDbQuery({
    required SurrealDb that,
    required String sql,
    String? vars,
  });

  Future<void> crateApiClientSurrealDbQueryBegin({required SurrealDb that});

  Future<void> crateApiClientSurrealDbQueryCancel({required SurrealDb that});

  Future<void> crateApiClientSurrealDbQueryCommit({required SurrealDb that});

  Future<String> crateApiClientSurrealDbSelect({
    required SurrealDb that,
    required String resource,
  });

  Future<String> crateApiClientSurrealDbSignin({
    required SurrealDb that,
    required String credentialsJson,
  });

  Future<String> crateApiClientSurrealDbSignup({
    required SurrealDb that,
    required String credentialsJson,
  });

  Future<String> crateApiClientSurrealDbTransaction({
    required SurrealDb that,
    required String statements,
    String? vars,
  });

  Future<String> crateApiClientSurrealDbUpdate({
    required SurrealDb that,
    required String resource,
    String? data,
  });

  Future<void> crateApiClientSurrealDbUseDb({
    required SurrealDb that,
    required String namespace,
    required String database,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SurrealDb;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SurrealDb;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SurrealDbPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiClientSurrealDbAuthenticate({
    required SurrealDb that,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbAuthenticateConstMeta,
        argValues: [that, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbAuthenticateConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_authenticate",
        argNames: ["that", "token"],
      );

  @override
  Future<void> crateApiClientSurrealDbClose({required SurrealDb that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbCloseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbCloseConstMeta =>
      const TaskConstMeta(debugName: "SurrealDb_close", argNames: ["that"]);

  @override
  Future<SurrealDb> crateApiClientSurrealDbConnect({
    required StorageMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_storage_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbConnectConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbConnectConstMeta =>
      const TaskConstMeta(debugName: "SurrealDb_connect", argNames: ["mode"]);

  @override
  Future<String> crateApiClientSurrealDbCreate({
    required SurrealDb that,
    required String resource,
    String? data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(resource, serializer);
          sse_encode_opt_String(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbCreateConstMeta,
        argValues: [that, resource, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbCreateConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_create",
        argNames: ["that", "resource", "data"],
      );

  @override
  Future<String> crateApiClientSurrealDbDelete({
    required SurrealDb that,
    required String resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(resource, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbDeleteConstMeta,
        argValues: [that, resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_delete",
        argNames: ["that", "resource"],
      );

  @override
  Future<void> crateApiClientSurrealDbExport({
    required SurrealDb that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbExportConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbExportConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_export",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateApiClientSurrealDbInvalidate({required SurrealDb that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbInvalidateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbInvalidateConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_invalidate",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiClientSurrealDbMerge({
    required SurrealDb that,
    required String resource,
    String? data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(resource, serializer);
          sse_encode_opt_String(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbMergeConstMeta,
        argValues: [that, resource, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbMergeConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_merge",
        argNames: ["that", "resource", "data"],
      );

  @override
  Future<String> crateApiClientSurrealDbQuery({
    required SurrealDb that,
    required String sql,
    String? vars,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(sql, serializer);
          sse_encode_opt_String(vars, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbQueryConstMeta,
        argValues: [that, sql, vars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbQueryConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_query",
        argNames: ["that", "sql", "vars"],
      );

  @override
  Future<void> crateApiClientSurrealDbQueryBegin({required SurrealDb that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbQueryBeginConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbQueryBeginConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_query_begin",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiClientSurrealDbQueryCancel({required SurrealDb that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbQueryCancelConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbQueryCancelConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_query_cancel",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiClientSurrealDbQueryCommit({required SurrealDb that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbQueryCommitConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbQueryCommitConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_query_commit",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiClientSurrealDbSelect({
    required SurrealDb that,
    required String resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(resource, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbSelectConstMeta,
        argValues: [that, resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbSelectConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_select",
        argNames: ["that", "resource"],
      );

  @override
  Future<String> crateApiClientSurrealDbSignin({
    required SurrealDb that,
    required String credentialsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(credentialsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbSigninConstMeta,
        argValues: [that, credentialsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbSigninConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_signin",
        argNames: ["that", "credentialsJson"],
      );

  @override
  Future<String> crateApiClientSurrealDbSignup({
    required SurrealDb that,
    required String credentialsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(credentialsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbSignupConstMeta,
        argValues: [that, credentialsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbSignupConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_signup",
        argNames: ["that", "credentialsJson"],
      );

  @override
  Future<String> crateApiClientSurrealDbTransaction({
    required SurrealDb that,
    required String statements,
    String? vars,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(statements, serializer);
          sse_encode_opt_String(vars, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbTransactionConstMeta,
        argValues: [that, statements, vars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_transaction",
        argNames: ["that", "statements", "vars"],
      );

  @override
  Future<String> crateApiClientSurrealDbUpdate({
    required SurrealDb that,
    required String resource,
    String? data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(resource, serializer);
          sse_encode_opt_String(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbUpdateConstMeta,
        argValues: [that, resource, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_update",
        argNames: ["that", "resource", "data"],
      );

  @override
  Future<void> crateApiClientSurrealDbUseDb({
    required SurrealDb that,
    required String namespace,
    required String database,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
            that,
            serializer,
          );
          sse_encode_String(namespace, serializer);
          sse_encode_String(database, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClientSurrealDbUseDbConstMeta,
        argValues: [that, namespace, database],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClientSurrealDbUseDbConstMeta =>
      const TaskConstMeta(
        debugName: "SurrealDb_use_db",
        argNames: ["that", "namespace", "database"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SurrealDb => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SurrealDb => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SurrealDb
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SurrealDbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SurrealDb
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SurrealDbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SurrealDb
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SurrealDbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  StorageMode dco_decode_box_autoadd_storage_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_storage_mode(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  StorageMode dco_decode_storage_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StorageMode_Memory();
      case 1:
        return StorageMode_Disk(path: dco_decode_String(raw[1]));
      case 2:
        return StorageMode_Remote(url: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SurrealDb
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SurrealDbImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SurrealDb
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SurrealDbImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SurrealDb
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SurrealDbImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  StorageMode sse_decode_box_autoadd_storage_mode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_storage_mode(deserializer));
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StorageMode sse_decode_storage_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return StorageMode_Memory();
      case 1:
        var var_path = sse_decode_String(deserializer);
        return StorageMode_Disk(path: var_path);
      case 2:
        var var_url = sse_decode_String(deserializer);
        return StorageMode_Remote(url: var_url);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    SurrealDb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SurrealDbImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    SurrealDb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SurrealDbImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSurrealDb(
    SurrealDb self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SurrealDbImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_storage_mode(
    StorageMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_storage_mode(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_storage_mode(StorageMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StorageMode_Memory():
        sse_encode_i_32(0, serializer);
      case StorageMode_Disk(path: final path):
        sse_encode_i_32(1, serializer);
        sse_encode_String(path, serializer);
      case StorageMode_Remote(url: final url):
        sse_encode_i_32(2, serializer);
        sse_encode_String(url, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class SurrealDbImpl extends RustOpaque implements SurrealDb {
  // Not to be used by end users
  SurrealDbImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SurrealDbImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SurrealDb,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SurrealDb,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SurrealDbPtr,
  );

  Future<void> authenticate({required String token}) => RustLib.instance.api
      .crateApiClientSurrealDbAuthenticate(that: this, token: token);

  Future<void> close() =>
      RustLib.instance.api.crateApiClientSurrealDbClose(that: this);

  Future<String> create({required String resource, String? data}) =>
      RustLib.instance.api.crateApiClientSurrealDbCreate(
        that: this,
        resource: resource,
        data: data,
      );

  Future<String> delete({required String resource}) => RustLib.instance.api
      .crateApiClientSurrealDbDelete(that: this, resource: resource);

  Future<void> export_({required String path}) => RustLib.instance.api
      .crateApiClientSurrealDbExport(that: this, path: path);

  Future<void> invalidate() =>
      RustLib.instance.api.crateApiClientSurrealDbInvalidate(that: this);

  Future<String> merge({required String resource, String? data}) => RustLib
      .instance
      .api
      .crateApiClientSurrealDbMerge(that: this, resource: resource, data: data);

  /// Execute a raw SQL query.
  /// `vars` should be a JSON string of bind variables, e.g. `{"id": "...", "val": 123}`.
  /// Execute a raw SQL query.
  /// `vars` should be a JSON string of bind variables, e.g. `{"id": "...", "val": 123}`.
  Future<String> query({required String sql, String? vars}) => RustLib
      .instance
      .api
      .crateApiClientSurrealDbQuery(that: this, sql: sql, vars: vars);

  Future<void> queryBegin() =>
      RustLib.instance.api.crateApiClientSurrealDbQueryBegin(that: this);

  Future<void> queryCancel() =>
      RustLib.instance.api.crateApiClientSurrealDbQueryCancel(that: this);

  Future<void> queryCommit() =>
      RustLib.instance.api.crateApiClientSurrealDbQueryCommit(that: this);

  Future<String> select({required String resource}) => RustLib.instance.api
      .crateApiClientSurrealDbSelect(that: this, resource: resource);

  Future<String> signin({required String credentialsJson}) =>
      RustLib.instance.api.crateApiClientSurrealDbSignin(
        that: this,
        credentialsJson: credentialsJson,
      );

  Future<String> signup({required String credentialsJson}) =>
      RustLib.instance.api.crateApiClientSurrealDbSignup(
        that: this,
        credentialsJson: credentialsJson,
      );

  Future<String> transaction({required String statements, String? vars}) =>
      RustLib.instance.api.crateApiClientSurrealDbTransaction(
        that: this,
        statements: statements,
        vars: vars,
      );

  Future<String> update({required String resource, String? data}) =>
      RustLib.instance.api.crateApiClientSurrealDbUpdate(
        that: this,
        resource: resource,
        data: data,
      );

  Future<void> useDb({required String namespace, required String database}) =>
      RustLib.instance.api.crateApiClientSurrealDbUseDb(
        that: this,
        namespace: namespace,
        database: database,
      );
}
