//! `spky agents init` — generate a tailored AGENTS.md in the consumer's app
//! root, parameterized by their parsed schema.
//!
//! The generated file is the first thing an AI coding agent reads when
//! dropped into a sp00ky-backed app: it describes the framework's mental
//! model, lists *this* app's tables (with CRDT/parent annotations), and
//! points at the per-package guides shipped under `node_modules/`.
use anyhow::{bail, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use crate::annotations;
use crate::backend::{self, ResolvedSchema, DEFAULT_CONFIG_PATH};
use crate::parser::{FieldType, SchemaParser};

const PREFIX: &str = "[sp00ky agents]";

pub fn init(force: bool, out: Option<&Path>, project_dir: &Path) -> Result<()> {
    let cfg = backend::load_config(&project_dir.join(DEFAULT_CONFIG_PATH));
    let resolved = ResolvedSchema::from_config(&cfg.schema);
    let schema_path = project_dir.join(&resolved.schema);

    if !schema_path.exists() {
        bail!(
            "schema source not found at {} — run `spky create` to scaffold a project, or check the `schema:` entry in sp00ky.yml",
            schema_path.display()
        );
    }

    let content = fs::read_to_string(&schema_path)
        .with_context(|| format!("reading schema {}", schema_path.display()))?;

    let mut parser = SchemaParser::new();
    parser
        .parse_file(&content)
        .context("Failed to parse schema for AGENTS.md generation")?;

    // Merge field annotations (same pattern handle_generate uses)
    let field_annotations = annotations::extract_field_annotations(&content);
    for ((table, field), anns) in &field_annotations {
        if let Some(t) = parser.tables.get_mut(table) {
            if let Some(f) = t.fields.get_mut(field) {
                f.annotations = anns.clone();
            }
        }
    }

    let rendered = render(&parser, &resolved, &cfg.client_types);

    let target = match out {
        Some(p) => p.to_path_buf(),
        None => project_dir.join("AGENTS.md"),
    };

    if target.exists() && !force {
        bail!(
            "{} {} already exists — re-run with --force to overwrite",
            PREFIX,
            target.display()
        );
    }

    if let Some(parent) = target.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).ok();
        }
    }
    fs::write(&target, rendered)
        .with_context(|| format!("writing {}", target.display()))?;

    eprintln!("{} wrote {}", PREFIX, target.display());
    Ok(())
}

fn render(
    parser: &SchemaParser,
    resolved: &ResolvedSchema,
    client_types: &[backend::ClientTypeConfig],
) -> String {
    let mut s = String::new();

    s.push_str("# AGENTS.md\n\n");
    s.push_str("> Auto-generated by `spky agents init` — re-run after schema changes to refresh.\n\n");

    s.push_str("## What this app uses\n\n");
    s.push_str("**sp00ky** — a reactive, local-first SurrealDB sync framework. The schema in `");
    s.push_str(&path_str(&resolved.schema));
    s.push_str("` is the source of truth; running `spky generate` produces typed `schema.gen.ts` (and Dart) bindings that the app imports. Local mutations are optimistic and drain through SSP to the remote SurrealDB.\n\n");
    s.push_str("This is not Mastra/LangChain/LangGraph (not an agent runtime), and it is not Convex/PowerSync (different sync model — sp00ky uses SurrealDB live queries + a local DBSP circuit).\n\n");

    s.push_str("## Mental model\n\n");
    s.push_str("```\n");
    s.push_str(".surql schema  ──spky generate──►  schema.gen.ts (typed)\n");
    s.push_str("                                        │\n");
    s.push_str("                                        ▼\n");
    s.push_str("                            SyncedDbConfig + Sp00kyProvider\n");
    s.push_str("                                        │\n");
    s.push_str("                            useDb() → db.create / db.update / db.delete / db.query\n");
    s.push_str("                                        │\n");
    s.push_str("                local cache (memory|IndexedDB)  ↔  SSP  ↔  remote SurrealDB\n");
    s.push_str("```\n\n");

    s.push_str("## Your tables\n\n");
    let user_tables: Vec<_> = parser
        .tables
        .iter()
        .filter(|(name, _)| !name.starts_with("_00_"))
        .collect();
    if user_tables.is_empty() {
        s.push_str("_(schema parser found no user tables — check that `");
        s.push_str(&path_str(&resolved.schema));
        s.push_str("` defines your domain)_\n\n");
    } else {
        for (name, table) in &user_tables {
            s.push_str(&format!("### `{}`\n\n", name));

            let mut crdt_fields: Vec<(&String, String)> = Vec::new();
            let mut parent_fields: Vec<(&String, String)> = Vec::new();
            let mut record_links: Vec<(&String, String)> = Vec::new();

            for (field_name, field_def) in &table.fields {
                for ann in &field_def.annotations {
                    if ann.name == "crdt" {
                        crdt_fields.push((
                            field_name,
                            ann.value.clone().unwrap_or_else(|| "text".to_string()),
                        ));
                    } else if ann.name == "parent" {
                        if let Some(target) = record_target(&field_def.field_type) {
                            parent_fields.push((field_name, target));
                        }
                    }
                }
                // Plain record links (no @parent)
                if !field_def.annotations.iter().any(|a| a.name == "parent") {
                    if let Some(target) = record_target(&field_def.field_type) {
                        record_links.push((field_name, target));
                    }
                }
            }

            if !crdt_fields.is_empty() {
                s.push_str("**CRDT fields** (use `useCrdtField`, not `useQuery`; pair writes with `{ debounced: true }`):\n");
                for (f, variant) in &crdt_fields {
                    s.push_str(&format!("- `{}.{}` (`@crdt {}`)\n", name, f, variant));
                }
                s.push('\n');
            }

            if !parent_fields.is_empty() {
                s.push_str("**Parent fields** (auto-populated server-side from auth context — do not write from client code):\n");
                for (f, target) in &parent_fields {
                    s.push_str(&format!("- `{}.{}` → `{}`\n", name, f, target));
                }
                s.push('\n');
            }

            if !record_links.is_empty() {
                s.push_str("**Record links:**\n");
                for (f, target) in &record_links {
                    s.push_str(&format!("- `{}.{}` → `{}`\n", name, f, target));
                }
                s.push('\n');
            }

            if crdt_fields.is_empty() && parent_fields.is_empty() && record_links.is_empty() {
                s.push_str("_(no CRDT, parent, or relationship annotations)_\n\n");
            }
        }
    }

    s.push_str("## Generated outputs\n\n");
    if client_types.is_empty() {
        s.push_str("_(no `clientTypes` configured in sp00ky.yml — add one to enable codegen)_\n\n");
    } else {
        for ct in client_types {
            s.push_str(&format!(
                "- `{}` — {}\n",
                ct.output,
                match ct.format {
                    backend::ClientFormat::Typescript => "TypeScript",
                    backend::ClientFormat::Dart => "Dart",
                }
            ));
        }
        s.push('\n');
    }

    s.push_str("## Where to look\n\n");
    s.push_str("- `node_modules/@spooky-sync/core/AGENTS.md` — sync engine, mutation queue, CRDT manager\n");
    s.push_str("- `node_modules/@spooky-sync/client-solid/AGENTS.md` — `useDb`, `useQuery`, `useCrdtField`, `Sp00kyProvider`\n");
    s.push_str("- `node_modules/@spooky-sync/query-builder/AGENTS.md` — typed query DSL\n");
    s.push_str("- `node_modules/@spooky-sync/cli/AGENTS.md` — `spky` subcommands and schema annotations\n");
    s.push_str("- `node_modules/@spooky-sync/devtools-mcp/AGENTS.md` — live MCP introspection\n\n");

    s.push_str("## Common gotchas\n\n");
    s.push_str("1. **Run `spky generate` after every schema edit.** Then `spky doctor` to confirm nothing else drifted.\n");
    s.push_str("2. **Record IDs are full strings.** `db.create('thread:abc', {...})`, not `db.create('thread', {id: 'abc'})`. Mint IDs with `new Uuid().toString()`.\n");
    s.push_str("3. **CRDT fields need `useCrdtField`.** Reading them via `useQuery` returns the last raw merged value, not a reactive Loro doc.\n");
    s.push_str("4. **`@parent` columns are read-only from the client.** They're populated server-side from the auth context.\n");
    s.push_str("5. **`useQuery` factories must end with `.build()`.** A bare builder hangs the hook.\n");
    s.push_str("6. **`db.useRemote(fn)` bypasses the local cache.** Use only for queries the type-safe builder can't express.\n\n");

    s.push_str("## Agent feedback loop\n\n");
    s.push_str("After any schema or config change:\n\n");
    s.push_str("```bash\n");
    s.push_str("spky generate          # refresh schema.gen.ts\n");
    s.push_str("spky doctor --json     # structured diagnostics — parse-and-grep ready\n");
    s.push_str("```\n\n");

    s.push_str("## Cookbook recipes\n\n");
    s.push_str("Render a parameterized snippet for any of these:\n\n");
    s.push_str("- `spky scaffold live-list --table <table>` — reactive list view\n");
    s.push_str("- `spky scaffold optimistic-mutation --table <table>` — create-record form\n");
    s.push_str("- `spky scaffold crdt-text-field --table <table> --field <field>` — collaborative editor\n\n");
    s.push_str("Run `spky scaffold list` for the full index, or read `node_modules/@spooky-sync/cli/templates/cookbook/INDEX.md`.\n");

    s
}

fn record_target(t: &FieldType) -> Option<String> {
    match t {
        FieldType::Record(target) => Some(target.clone()),
        FieldType::Option(inner) => record_target(inner),
        FieldType::Array(inner) => record_target(inner),
        _ => None,
    }
}

fn path_str(p: &PathBuf) -> String {
    p.display().to_string()
}
