use anyhow::{bail, Context, Result};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

use crate::backend::{BackendProcessor, DeployMode};
use crate::parser::SchemaParser;
use crate::schema_builder::SchemaBuilderConfig;
use crate::schema_diff;
use crate::schema_extract;
use crate::sp00ky::generate_sp00ky_events;
use crate::surreal_client::{MigrationDB, SurrealClient};
use crate::ui;

// Subtle ANSI colors for the one-shot `migrate create` / `migrate fix`
// output. The apply path renders through `crate::ui` instead.
const GREEN: &str = "\x1b[32m";
const YELLOW: &str = "\x1b[33m";
const RED: &str = "\x1b[31m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
const RESET: &str = "\x1b[0m";

/// A migration discovered on the filesystem.
pub(crate) struct FilesystemMigration {
    pub version: String,
    pub name: String,
    pub path: PathBuf,
}

/// Scan the migrations directory and return sorted migrations.
///
/// Expects flat `.surql` files named `{14-digit-timestamp}_{name}.surql`.
pub(crate) fn scan_migrations(migrations_dir: &Path) -> Result<Vec<FilesystemMigration>> {
    if !migrations_dir.exists() {
        return Ok(vec![]);
    }

    let mut migrations = Vec::new();

    for entry in fs::read_dir(migrations_dir).context("Failed to read migrations directory")? {
        let entry = entry?;
        let path = entry.path();

        // Only consider .surql files
        if path.is_dir() || path.extension().and_then(|e| e.to_str()) != Some("surql") {
            continue;
        }

        let file_stem = match path.file_stem().and_then(|n| n.to_str()) {
            Some(name) => name.to_string(),
            None => continue,
        };

        // Parse "{version}_{name}" pattern
        let underscore_pos = match file_stem.find('_') {
            Some(pos) => pos,
            None => continue,
        };

        let version = file_stem[..underscore_pos].to_string();
        let name = file_stem[underscore_pos + 1..].to_string();

        // Validate version looks like a timestamp
        if version.len() != 14 || !version.chars().all(|c| c.is_ascii_digit()) {
            continue;
        }

        migrations.push(FilesystemMigration {
            version,
            name,
            path,
        });
    }

    migrations.sort_by(|a, b| a.version.cmp(&b.version));
    Ok(migrations)
}

/// Compute SHA-256 checksum of a string.
pub(crate) fn checksum_str(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Compute SHA-256 checksum of a file's contents.
pub(crate) fn checksum(path: &Path) -> Result<String> {
    let content = fs::read_to_string(path)
        .context(format!("Failed to read file for checksum: {:?}", path))?;
    Ok(checksum_str(&content))
}

/// Sanitize a migration name: lowercase, replace spaces/hyphens with underscores.
pub(crate) fn sanitize_name(name: &str) -> String {
    name.to_lowercase()
        .replace([' ', '-'], "_")
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '_')
        .collect()
}

// ── Checksum validation ──────────────────────────────────────────────────────

/// Validate that applied migration checksums match the filesystem.
///
/// Returns a list of warning messages for non-fatal issues (e.g. missing files on disk).
/// Bails on checksum mismatches.
pub fn validate_applied_checksums(
    applied: &[crate::surreal_client::AppliedMigration],
    filesystem: &[FilesystemMigration],
) -> Result<Vec<String>> {
    let mut warnings = Vec::new();

    for am in applied {
        if let Some(fm) = filesystem.iter().find(|f| f.version == am.version) {
            if !fm.path.exists() {
                warnings.push(format!(
                    "Applied migration {}_{} is missing from disk",
                    am.version, am.name
                ));
                continue;
            }
            let disk_checksum = checksum(&fm.path)?;
            if disk_checksum != am.checksum {
                bail!(
                    "Checksum mismatch for migration {}_{}\n  Expected: {}\n  Found:    {}\n\nThe migration file has been modified after it was applied. This is dangerous.\nIf intentional, use `sp00ky migrate fix --fix-checksums` to update stored checksums.",
                    am.version,
                    am.name,
                    am.checksum,
                    disk_checksum
                );
            }
        } else {
            warnings.push(format!(
                "Applied migration {}_{} not found on disk (drift detected)",
                am.version, am.name
            ));
        }
    }

    Ok(warnings)
}

// ── Commands ────────────────────────────────────────────────────────────────

/// Create a new migration file with auto-diff support.
///
/// When `builder_config` is provided, the migration is auto-generated by:
/// 1. Building the new schema from sources
/// 2. Extracting the old schema (from live DB or ephemeral DB with existing migrations)
/// 3. Computing the diff and writing only the delta
///
/// Falls back to the old behavior (empty template or schema dump) when `builder_config` is None.
pub fn create(
    migrations_dir: &Path,
    name: &str,
    schema_path: Option<&Path>,
    builder_config: Option<&SchemaBuilderConfig>,
    conn: Option<(&str, &str, &str, &str, &str)>,
) -> Result<()> {
    let sanitized = sanitize_name(name);
    let timestamp = chrono::Utc::now().format("%Y%m%d%H%M%S").to_string();
    let file_name = format!("{}_{}.surql", timestamp, sanitized);
    let file_path = migrations_dir.join(&file_name);

    fs::create_dir_all(migrations_dir).context(format!(
        "Failed to create migrations directory: {:?}",
        migrations_dir
    ))?;

    // Try auto-diff if builder_config is provided
    if let Some(config) = builder_config {
        // 0. Early checksum validation when a DB connection is available
        if let Some((url, ns, db, user, pass)) = conn {
            let client = SurrealClient::new(url, ns, db, user, pass);
            if client.ping().is_ok() {
                if let Ok(()) = client.ensure_migration_table() {
                    if let Ok(applied) = client.get_applied_migrations() {
                        let existing = scan_migrations(migrations_dir)?;
                        let warnings = validate_applied_checksums(&applied, &existing)?;
                        for warning in &warnings {
                            println!("{YELLOW}WARNING: {warning}{RESET}");
                        }
                    }
                }
            }
        }

        // 1. Build new schema
        println!("Building target schema...");
        let new_schema_sql = crate::schema_builder::build_server_schema(config)?;

        // 2. Get old and new schemas (both normalized through SurrealDB)
        println!("Extracting current schema...");
        let existing_migrations = scan_migrations(migrations_dir)?;
        let (old_schema, new_schema) = if let Some((url, ns, db, user, pass)) = conn {
            // Live DB: extract old from live, normalize new through ephemeral.
            // Restore the live side's redacted signing key to the source
            // placeholder so it matches the (also-restored) new side instead of
            // diffing as `[REDACTED]` vs `{{...}}`.
            let client = SurrealClient::new(url, ns, db, user, pass);
            let old = schema_extract::restore_redacted_keys(
                &schema_extract::extract_schema_from_db(&client)?,
                &new_schema_sql,
            );
            let new = schema_extract::normalize_schema_via_ephemeral_db(&new_schema_sql)?;
            (old, new)
        } else if existing_migrations.is_empty() {
            // No prior migrations → old schema is empty, normalize new through ephemeral
            println!("  No existing migrations found — generating initial migration.");
            let new = schema_extract::normalize_schema_via_ephemeral_db(&new_schema_sql)?;
            (String::new(), new)
        } else {
            // Standard case: both old and new normalized through ephemeral
            schema_extract::extract_old_and_new_schemas(migrations_dir, &new_schema_sql)?
        };

        // 3. Diff
        let diff = schema_diff::diff_schemas(&old_schema, &new_schema);

        if diff.is_empty() {
            println!("{DIM}No schema changes detected.{RESET}");
            return Ok(());
        }

        // 4. Write migration (with OVERWRITE so it's idempotent inside transactions)
        let migration_body = make_defines_overwrite(&diff.to_migration_string());
        let content = format!(
            "-- Migration: {}\n-- Created: {}\n\n{}",
            sanitized,
            chrono::Utc::now().to_rfc3339(),
            migration_body,
        );

        fs::write(&file_path, content)
            .context(format!("Failed to write migration file: {:?}", file_path))?;

        println!("{GREEN}Created migration: {}{RESET}", file_name);
        println!("  {}", file_path.display());
        println!(
            "  {GREEN}+{} addition(s){RESET}, {RED}-{} removal(s){RESET}, {YELLOW}~{} modification(s){RESET}",
            diff.added.len(),
            diff.removed.len(),
            diff.modified.len()
        );

        return Ok(());
    }

    // Fallback: legacy behavior (empty template or schema dump)
    let content = if let Some(schema) = schema_path {
        let schema_content = fs::read_to_string(schema)
            .context(format!("Failed to read schema file: {:?}", schema))?;
        format!(
            "-- Migration: {}\n-- Created: {}\n--\n-- WARNING: This file was pre-populated with the full schema.\n-- Edit this to contain ONLY the incremental changes for this migration.\n\n{}",
            sanitized,
            chrono::Utc::now().to_rfc3339(),
            schema_content
        )
    } else {
        format!(
            "-- Migration: {}\n-- Created: {}\n--\n-- Write your forward migration SurrealQL here.\n",
            sanitized,
            chrono::Utc::now().to_rfc3339()
        )
    };

    fs::write(&file_path, content)
        .context(format!("Failed to write migration file: {:?}", file_path))?;

    println!("{GREEN}Created migration: {}{RESET}", file_name);
    println!("  {}", file_path.display());

    Ok(())
}

/// Apply all pending migrations in order.
pub fn apply(client: &dyn MigrationDB, migrations_dir: &Path) -> Result<()> {
    apply_impl(client, migrations_dir, None)
}

/// Like [`apply`], but substitutes `{{VAULT_KEY}}` placeholders in each migration
/// with the provided secrets (e.g. from the vault) before executing, and errors
/// on any unresolved placeholder.
///
/// This is the REAL apply path (used by the LegacyEngine), so project secrets —
/// e.g. an EdDSA signing key for `DEFINE ACCESS ... WITH JWT` — can live in the
/// vault instead of being committed to the schema. The ephemeral schema-diff
/// replay keeps using [`apply`] (placeholders left literal), so the "old" and
/// "new" schemas still match and the placeholder never reads as drift.
pub fn apply_with_secrets(
    client: &dyn MigrationDB,
    migrations_dir: &Path,
    secrets: &[(String, String)],
) -> Result<()> {
    apply_impl(client, migrations_dir, Some(secrets))
}

fn apply_impl(
    client: &dyn MigrationDB,
    migrations_dir: &Path,
    secrets: Option<&[(String, String)]>,
) -> Result<()> {
    client
        .ensure_ns_db()
        .context("Failed to ensure namespace/database exist")?;
    client.ping().context("Cannot connect to SurrealDB")?;
    client.ensure_migration_table()?;

    let applied = client.get_applied_migrations()?;
    let filesystem = scan_migrations(migrations_dir)?;

    // Integrity check: verify checksums of applied migrations
    let warnings = validate_applied_checksums(&applied, &filesystem)?;
    for warning in &warnings {
        ui::warn(warning);
    }

    // Find pending migrations
    let applied_versions: Vec<&str> = applied.iter().map(|a| a.version.as_str()).collect();
    let pending: Vec<&FilesystemMigration> = filesystem
        .iter()
        .filter(|f| !applied_versions.contains(&f.version.as_str()))
        .collect();

    if pending.is_empty() {
        ui::step("Migrations").done("up to date");
        return Ok(());
    }

    let summary = ui::step("Migrations");
    summary.set_message(format!("applying {} pending…", pending.len()));

    for migration in &pending {
        if !migration.path.exists() {
            bail!(
                "Missing migration file for {}_{}",
                migration.version,
                migration.name
            );
        }

        let raw = fs::read_to_string(&migration.path)
            .context(format!("Failed to read {:?}", migration.path))?;

        // Checksum the on-disk file (pre-substitution) so the recorded checksum
        // matches the committed migration regardless of secret values.
        let hash = checksum(&migration.path)?;

        let sql = match secrets {
            Some(s) => substitute_secrets(&raw, s).context(format!(
                "Failed to substitute secrets in migration {}_{}",
                migration.version, migration.name
            ))?,
            None => raw,
        };

        let step = ui::step(format!("  {}_{}", migration.version, migration.name));

        // Apply migration statements directly (SurrealDB DDL doesn't support transactions)
        if let Err(e) = client.execute(&sql) {
            step.fail("failed");
            summary.fail(format!("stopped at {}_{}", migration.version, migration.name));
            return Err(e).context(format!(
                "Failed to apply migration {}_{}",
                migration.version, migration.name
            ));
        }

        if let Err(e) = client.record_migration(&migration.version, &migration.name, &hash) {
            step.fail("applied, but could not record");
            summary.fail(format!("stopped at {}_{}", migration.version, migration.name));
            return Err(e);
        }

        step.done("");
    }

    summary.done(format!("{} applied", pending.len()));
    Ok(())
}

/// Replace `{{KEY}}` placeholders (UPPER_SNAKE keys, optional inner spaces) in
/// migration SQL with the matching secret value. After substitution, ANY
/// remaining `{{NAME}}` placeholder is an error — so a missing secret fails the
/// apply loudly instead of writing a broken value (e.g. a literal `{{...}}` as a
/// JWT signing key).
///
/// Only `{{UPPER_SNAKE}}` tokens are treated as placeholders, so ordinary text /
/// comments that happen to contain braces are left untouched.
pub fn substitute_secrets(sql: &str, secrets: &[(String, String)]) -> Result<String> {
    let mut out = sql.to_string();
    for (key, value) in secrets {
        if !is_placeholder_key(key) {
            continue;
        }
        out = out.replace(&format!("{{{{{key}}}}}"), value);
        out = out.replace(&format!("{{{{ {key} }}}}"), value);
    }

    let unresolved = find_unresolved_placeholders(&out);
    if !unresolved.is_empty() {
        bail!(
            "unresolved schema placeholder(s): {} — provide them as vault secrets \
             (sp00ky.yml env.vault) so they are injected at apply time",
            unresolved.join(", ")
        );
    }
    Ok(out)
}

/// A placeholder key is UPPER_SNAKE: starts with a letter/underscore, then
/// uppercase letters, digits, or underscores.
fn is_placeholder_key(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_uppercase() || c == '_' => {}
        _ => return false,
    }
    s.chars()
        .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_')
}

/// Scan for any remaining `{{UPPER_SNAKE}}` placeholder tokens (UTF-8 safe: uses
/// byte-offset `find` only on the ASCII `{{`/`}}` delimiters).
fn find_unresolved_placeholders(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut rest = s;
    while let Some(start) = rest.find("{{") {
        let after = &rest[start + 2..];
        match after.find("}}") {
            Some(end) => {
                let inner = after[..end].trim();
                if is_placeholder_key(inner) {
                    out.push(inner.to_string());
                }
                rest = &after[end + 2..];
            }
            None => break,
        }
    }
    out
}

/// Fix schema drift and/or update stored checksums for modified migration files.
///
/// When `fix_checksums` is true:
///   - Compares on-disk checksums against stored checksums in the DB
///   - Updates any mismatched stored checksums to match the current file contents
///
/// When the live DB is reachable and `fix_checksums` is not the only goal:
///   1. Replay all migrations through an ephemeral DB → `expected_schema`
///   2. Extract live DB schema → `actual_schema`
///   3. `diff_schemas(&actual_schema, &expected_schema)` → corrective diff
///   4. If non-empty, write a corrective migration file
pub fn fix(client: &dyn MigrationDB, migrations_dir: &Path, fix_checksums: bool) -> Result<()> {
    // Ensure the DB is reachable
    client.ensure_ns_db().context(
        "Cannot connect to SurrealDB.\n\
         The `migrate fix` command requires a running database.\n\
         Start your database first (e.g. `sp00ky dev`) or pass --url to point at a running instance."
    )?;
    client.ping().context("Cannot connect to SurrealDB")?;
    client.ensure_migration_table()?;

    let applied = client.get_applied_migrations()?;
    let filesystem = scan_migrations(migrations_dir)?;

    // Fix checksums if requested (do this first so subsequent operations see clean state)
    if fix_checksums {
        let mut fixed_count = 0;
        for am in &applied {
            if let Some(fm) = filesystem.iter().find(|f| f.version == am.version) {
                if !fm.path.exists() {
                    continue;
                }
                let disk_checksum = checksum(&fm.path)?;
                if disk_checksum != am.checksum {
                    println!(
                        "  {YELLOW}Updating checksum for {}_{}{RESET}",
                        am.version, am.name
                    );
                    client.update_migration_checksum(&am.version, &disk_checksum)?;
                    fixed_count += 1;
                }
            }
        }
        if fixed_count > 0 {
            println!("{GREEN}Updated {} checksum(s).{RESET}", fixed_count);
        } else {
            println!("{DIM}All checksums are up to date.{RESET}");
        }
    }

    // Schema drift detection: replay migrations vs live DB
    println!("Replaying migrations through ephemeral DB...");
    let expected_schema = schema_extract::extract_expected_schema_from_migrations(migrations_dir)?;

    println!("Extracting live DB schema...");
    let actual_schema = extract_live_schema(client)?;

    let diff = schema_diff::diff_schemas(&actual_schema, &expected_schema);

    if diff.is_empty() {
        println!("{GREEN}{BOLD}Live DB schema matches expected schema. No corrective migration needed.{RESET}");
        return Ok(());
    }

    // Write corrective migration
    println!(
        "Schema drift detected: {GREEN}+{} addition(s){RESET}, {RED}-{} removal(s){RESET}, {YELLOW}~{} modification(s){RESET}",
        diff.added.len(),
        diff.removed.len(),
        diff.modified.len()
    );
    diff.print_colored();

    let timestamp = chrono::Utc::now().format("%Y%m%d%H%M%S").to_string();
    let file_name = format!("{}_corrective_fix.surql", timestamp);
    let file_path = migrations_dir.join(&file_name);

    fs::create_dir_all(migrations_dir)?;

    let migration_body = diff.to_migration_string();
    let content = format!(
        "-- Corrective migration (generated by `sp00ky migrate fix`)\n-- Created: {}\n\n{}",
        chrono::Utc::now().to_rfc3339(),
        migration_body,
    );

    fs::write(&file_path, &content)?;
    println!("{GREEN}Created corrective migration: {}{RESET}", file_name);
    println!("  {}", file_path.display());
    println!("\nReview the migration, then run `sp00ky migrate apply` to apply it.");

    Ok(())
}

/// Extract the full schema from a live DB via the MigrationDB trait.
///
/// Queries INFO FOR DB and INFO FOR TABLE for each discovered table,
/// collecting all DEFINE statements (excluding internal `_00_migrations`).
fn extract_live_schema(client: &dyn MigrationDB) -> Result<String> {
    let db_info_responses = client.execute("INFO FOR DB;")?;
    let db_info = db_info_responses
        .into_iter()
        .next()
        .and_then(|r| r.result)
        .unwrap_or(serde_json::Value::Null);

    let mut statements = Vec::new();
    let mut table_names = Vec::new();

    if let Some(obj) = db_info.as_object() {
        for (section, values) in obj {
            if let Some(inner_obj) = values.as_object() {
                for (name, define_stmt) in inner_obj {
                    if section == "tables" && name == "_00_migrations" {
                        continue;
                    }
                    if let Some(stmt_str) = define_stmt.as_str() {
                        let trimmed = stmt_str.trim();
                        if trimmed.ends_with(';') {
                            statements.push(trimmed.to_string());
                        } else {
                            statements.push(format!("{};", trimmed));
                        }
                    }
                    if section == "tables" {
                        table_names.push(name.clone());
                    }
                }
            }
        }

        for table_name in &table_names {
            let table_responses = client.execute(&format!("INFO FOR TABLE {};", table_name))?;
            let table_info = table_responses
                .into_iter()
                .next()
                .and_then(|r| r.result)
                .unwrap_or(serde_json::Value::Null);

            if let Some(table_obj) = table_info.as_object() {
                for (section, values) in table_obj {
                    if let Some(inner_obj) = values.as_object() {
                        for (name, define_stmt) in inner_obj {
                            if section == "fields" && name.ends_with(".*") {
                                continue;
                            }
                            if let Some(stmt_str) = define_stmt.as_str() {
                                let trimmed = stmt_str.trim();
                                if trimmed.ends_with(';') {
                                    statements.push(trimmed.to_string());
                                } else {
                                    statements.push(format!("{};", trimmed));
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    Ok(statements.join("\n"))
}

/// Inject `OVERWRITE` into `DEFINE` statements that don't already have it,
/// so the SQL is idempotent (safe to re-run against an existing DB).
///
/// Transforms:  `DEFINE TABLE foo`  → `DEFINE TABLE OVERWRITE foo`
/// Leaves alone: `DEFINE TABLE OVERWRITE foo` (already has it)
///               `DEFINE EVENT OVERWRITE ...` (already has it, e.g. from generate_sp00ky_events)
fn make_defines_overwrite(sql: &str) -> String {
    // Patterns: DEFINE <KEYWORD> → DEFINE <KEYWORD> OVERWRITE
    // We insert OVERWRITE after the keyword when it's not already present.
    let mut result = sql.to_string();
    for keyword in &[
        "TABLE", "FIELD", "EVENT", "INDEX", "ACCESS", "BUCKET", "API", "FUNCTION", "ANALYZER",
        "PARAM",
    ] {
        // Match "DEFINE <KEYWORD> " but NOT "DEFINE <KEYWORD> OVERWRITE "
        let pattern = format!("DEFINE {} ", keyword);
        let with_overwrite = format!("DEFINE {} OVERWRITE ", keyword);
        // Replace all, but skip those that already have OVERWRITE
        result = result.replace(&with_overwrite, &format!("__PLACEHOLDER_{}__", keyword));
        result = result.replace(&pattern, &with_overwrite);
        result = result.replace(&format!("__PLACEHOLDER_{}__", keyword), &with_overwrite);
    }
    result
}

/// Drop `DEFINE INDEX` statements whose definition already matches the live
/// index (per `INFO FOR TABLE`), so re-applying the internal schema never
/// rebuilds an index that has not changed. Returns the SQL and how many were
/// dropped.
///
/// `DEFINE INDEX OVERWRITE` rebuilds the index from scratch inside the apply
/// request, one entry per row. On `_00_version` that is one entry per synced
/// row (737k on whitepawn staging): long enough to hit the CLI's HTTP timeout,
/// and an interrupted rebuild leaves the unique index partially populated.
/// `_00_version.record_id` is the lookup every `_00_<table>_mutation` event
/// does to stamp `_00_rv`; a missing entry stamps NONE, the row is published
/// at version 1, and every peer holding it at >= 1 keeps its stale copy for
/// good (measured: 35% of rows, two chat clients each rendering their own
/// last write). See
/// docs/surrealdb-bugs/unique-index-partial-after-overwrite-rebuild.md.
///
/// A changed definition, a missing index, or an unreadable `INFO FOR TABLE`
/// keeps the statement: a rebuild is then the right thing, or the safe one.
fn prune_unchanged_index_defines(client: &dyn MigrationDB, sql: &str) -> (String, usize) {
    use std::collections::HashMap;
    // table -> its live indexes (name -> definition); None when INFO failed.
    let mut live: HashMap<String, Option<HashMap<String, String>>> = HashMap::new();
    let mut out = String::with_capacity(sql.len());
    let mut pruned = 0;
    let mut cursor = 0;
    while let Some(rel) = sql[cursor..].find("DEFINE INDEX ") {
        let start = cursor + rel;
        out.push_str(&sql[cursor..start]);
        let end = sql[start..].find(';').map(|i| start + i + 1).unwrap_or(sql.len());
        let stmt = &sql[start..end];
        cursor = end;
        // A match on a `--` comment line is not a statement.
        let line_start = sql[..start].rfind('\n').map(|i| i + 1).unwrap_or(0);
        if sql[line_start..start].trim_start().starts_with("--") {
            out.push_str(stmt);
            continue;
        }
        let Some((name, table)) = index_define_target(stmt) else {
            out.push_str(stmt);
            continue;
        };
        let indexes = live
            .entry(table.clone())
            .or_insert_with(|| read_live_indexes(client, &table));
        let unchanged = indexes
            .as_ref()
            .and_then(|m| m.get(&name))
            .map(|def| normalize_index_define(def) == normalize_index_define(stmt))
            .unwrap_or(false);
        if unchanged {
            pruned += 1;
            out.push_str(&format!("-- index {name} on {table} unchanged; not rebuilt"));
        } else {
            out.push_str(stmt);
        }
    }
    out.push_str(&sql[cursor..]);
    (out, pruned)
}

/// `(index name, table)` of a `DEFINE INDEX [OVERWRITE|IF NOT EXISTS] <name> ON
/// [TABLE] <table> ...` statement, or `None` if it does not parse as one.
fn index_define_target(stmt: &str) -> Option<(String, String)> {
    let mut toks = stmt.split_whitespace();
    if !toks.next()?.eq_ignore_ascii_case("DEFINE") || !toks.next()?.eq_ignore_ascii_case("INDEX") {
        return None;
    }
    let mut name = toks.next()?;
    if name.eq_ignore_ascii_case("OVERWRITE") {
        name = toks.next()?;
    } else if name.eq_ignore_ascii_case("IF") {
        toks.next()?; // NOT
        toks.next()?; // EXISTS
        name = toks.next()?;
    }
    if !toks.next()?.eq_ignore_ascii_case("ON") {
        return None;
    }
    let mut table = toks.next()?;
    if table.eq_ignore_ascii_case("TABLE") {
        table = toks.next()?;
    }
    Some((name.to_string(), table.trim_end_matches(';').to_string()))
}

/// Canonical form of an index definition so ours (`OVERWRITE`, `ON TABLE`,
/// `COLUMNS`, line breaks) compares equal to what `INFO FOR TABLE` prints
/// (`ON`, `FIELDS`, one line). Anything else that differs is a real change.
fn normalize_index_define(stmt: &str) -> String {
    let body = stmt.trim().trim_end_matches(';');
    let raw: Vec<&str> = body.split_whitespace().collect();
    let mut toks: Vec<String> = Vec::with_capacity(raw.len());
    let mut i = 0;
    while i < raw.len() {
        let t = raw[i];
        let is = |s: &str| t.eq_ignore_ascii_case(s);
        let after_on = toks.last().map(|p| p.eq_ignore_ascii_case("ON")).unwrap_or(false);
        if is("OVERWRITE") {
        } else if is("IF")
            && raw.get(i + 1).map(|x| x.eq_ignore_ascii_case("NOT")).unwrap_or(false)
            && raw.get(i + 2).map(|x| x.eq_ignore_ascii_case("EXISTS")).unwrap_or(false)
        {
            i += 2;
        } else if is("TABLE") && after_on {
        } else if is("COLUMNS") {
            toks.push("FIELDS".to_string());
        } else {
            toks.push(t.to_string());
        }
        i += 1;
    }
    toks.join(" ").replace(", ", ",").replace(',', ", ")
}

/// The live `indexes` map of `INFO FOR TABLE <table>`, or `None` when the
/// table does not exist or the query failed.
fn read_live_indexes(
    client: &dyn MigrationDB,
    table: &str,
) -> Option<std::collections::HashMap<String, String>> {
    let responses = client.execute(&format!("INFO FOR TABLE {table};")).ok()?;
    let ok = responses.into_iter().find(|r| r.status == "OK")?;
    let indexes = ok.result?.get("indexes")?.as_object()?.clone();
    Some(
        indexes
            .into_iter()
            .filter_map(|(k, v)| v.as_str().map(|s| (k, s.to_string())))
            .collect(),
    )
}

/// True when a full schema re-apply is forced (bypass the hash-skip). Set by the
/// `--force-schema` flag (which exports this env) or by exporting it directly.
/// Read from the env so every apply path — deploy phase 1 & 2, `migrate prod`,
/// `migrate apply`, `dev`, `backup restore` — is covered without threading a
/// `force` parameter through every call site.
fn force_schema_reapply() -> bool {
    std::env::var("SPKY_FORCE_SCHEMA").is_ok()
}

/// Read the stored schema hash for `id` from `_00_schema_state`. Returns `None`
/// when the table doesn't exist yet (first apply), the row is missing, or the
/// query errors — all of which mean "no stored hash, apply".
fn read_stored_schema_hash(client: &dyn MigrationDB, id: &str) -> Option<String> {
    // Access by record id (`_00_schema_state:<id>`) — `id` is SurrealDB's
    // built-in record identifier, so a `WHERE id = '<id>'` filter would never
    // match the string against the full record id.
    let q = format!("SELECT hash FROM _00_schema_state:{};", id);
    let responses = client.execute(&q).ok()?;
    // execute() returns one SurrealResponse per statement; take the first OK one
    // with a non-empty result array and read its `hash` field.
    for r in responses {
        if r.status != "OK" {
            continue;
        }
        if let Some(arr) = r.result.as_ref().and_then(|v| v.as_array()) {
            if let Some(hash) = arr
                .first()
                .and_then(|row| row.get("hash"))
                .and_then(|h| h.as_str())
            {
                return Some(hash.to_string());
            }
        }
    }
    None
}

/// Record the applied schema hash for `id` in `_00_schema_state` (best-effort:
/// a failure here only costs a redundant re-apply next time, so it warns rather
/// than failing the migration).
fn record_schema_hash(client: &dyn MigrationDB, id: &str, hash: &str) {
    let q = format!(
        "UPSERT _00_schema_state:{id} SET hash = '{hash}', updated_at = time::now();",
        id = id,
        hash = hash
    );
    if let Err(e) = client.execute(&q) {
        ui::warn(format!("failed to record schema hash for '{id}': {e:?}"));
    }
}

/// Apply the remote-functions SQL blob, skipping the execute when its hash is
/// unchanged from the last successful apply (unless `SPKY_FORCE_SCHEMA` is set).
/// Shared by the deploy path (cloud.rs) and the migration engine
/// (sp00ky_engine.rs) so the skip logic lives in one place.
pub fn apply_remote_functions_if_changed(client: &dyn MigrationDB, sql: &str) -> Result<()> {
    let hash = checksum_str(sql);
    let step = ui::step("Remote functions");
    if !force_schema_reapply() && read_stored_schema_hash(client, "remote_fns").as_deref() == Some(&hash)
    {
        step.skip("unchanged");
        return Ok(());
    }
    if let Err(e) = client.execute(sql) {
        step.fail("failed");
        return Err(e).context("Failed to apply remote functions");
    }
    record_schema_hash(client, "remote_fns", &hash);
    step.done("applied");
    Ok(())
}

/// Apply internal Sp00ky schema (meta tables + per-table events) after user migrations.
///
/// This is idempotent — all statements use `DEFINE ... OVERWRITE` or `DEFINE ... SCHEMALESS`.
/// Not tracked in `_00_migrations` table.
pub fn apply_internal_schema(
    client: &dyn MigrationDB,
    schema_input_path: &Path,
    config_path: Option<&Path>,
    mode: &DeployMode,
    endpoint: Option<&str>,
    secret: Option<&str>,
) -> Result<()> {
    let step = ui::step("Internal schema");

    // 1. Read source schema + process backends
    let mut content = fs::read_to_string(schema_input_path).context(format!(
        "Failed to read schema file: {:?}",
        schema_input_path
    ))?;

    let mut backend_processor = BackendProcessor::new();
    if let Some(cp) = config_path {
        if cp.exists() {
            backend_processor.process(cp)?;
            content.push('\n');
            content.push_str(&backend_processor.schema_appends);
        }
    }

    // 2. Parse schema to get table map
    let mut parser = SchemaParser::new();
    parser
        .parse_file(&content)
        .context("Failed to parse schema for internal schema generation")?;

    let table_count = parser.tables.len();
    ui::detail(format!(
        "{} user table(s): {}",
        table_count,
        parser.tables.keys().cloned().collect::<Vec<_>>().join(", ")
    ));
    step.set_message(format!("assembling · {} tables", table_count));

    // 3. Build internal SQL
    let mut internal_sql = String::new();

    // 3a. Meta tables (remote)
    ui::detail("meta tables (remote)");
    let mut meta_tables_remote = include_str!("meta_tables_remote.surql").to_string();

    // Substitute the {{CRDT_UPDATE_RULE}} placeholder. Same code path used
    // by schema_builder.rs and main.rs codegen so the rule renders
    // consistently.
    meta_tables_remote =
        crate::schema_builder::substitute_crdt_update_rule(&meta_tables_remote, &content, &parser);

    // Replace unregister_view for singlenode/cluster mode — uses $sp00ky_endpoint param
    if *mode == DeployMode::Singlenode || *mode == DeployMode::Cluster {
        let unregister_call = "let $result = mod::dbsp::unregister_view(<string>$before.id);";
        let unregister_http =
            "let $payload = { id: <string>$before.id };\n    let $result = http::post($sp00ky_endpoint + '/view/unregister', $payload, { \"Authorization\": \"Bearer \" + $sp00ky_secret });";
        meta_tables_remote = meta_tables_remote.replace(unregister_call, unregister_http);
    }

    // Make all DEFINE statements idempotent by injecting OVERWRITE
    meta_tables_remote = make_defines_overwrite(&meta_tables_remote);

    internal_sql.push_str(&meta_tables_remote);
    internal_sql.push('\n');

    // Scheduling tables (`_00_schedule*`). A separate file so the engine crate
    // can include_str! exactly this DDL in its tests; already all-OVERWRITE, so
    // it goes in AFTER make_defines_overwrite rather than through it.
    internal_sql.push_str(include_str!("schedule_tables.surql"));
    internal_sql.push('\n');

    // 3b. Per-table sp00ky events (mutation + delete for versioning & ingest)
    let sp00ky_events = generate_sp00ky_events(
        &parser.tables,
        &content,
        false, // is_client = false (server-side events)
        mode,
        endpoint,
        secret,
    );
    let event_count = sp00ky_events.matches("DEFINE EVENT").count();
    ui::detail(format!("{} per-table events", event_count));
    internal_sql.push_str(&sp00ky_events);

    // 3c. Platform job fields on outbox tables. The SSP stamps `assignee`
    // when it claims a job on pickup/recover; a SCHEMAFULL user outbox table
    // without the field rejects the stamp and the recovery sweep can then
    // never actually recover a stuck job (it re-dispatches every 30s
    // forever). IF NOT EXISTS so a user's own definition always wins — and
    // it must stay AFTER the make_defines_overwrite call above, which would
    // corrupt an IF NOT EXISTS clause with OVERWRITE.
    let outbox = crate::schema_builder::outbox_tables(&backend_processor);
    if !outbox.is_empty() {
        ui::detail(format!(
            "platform job fields on outbox table(s): {}",
            outbox.join(", ")
        ));
        internal_sql.push('\n');
        internal_sql.push_str(&crate::schema_builder::build_outbox_platform_fields(
            outbox.iter().map(String::as_str),
            mode,
        ));
    }

    // 4. Skip when the assembled schema is byte-identical to the last applied one.
    // Every statement is `DEFINE ... OVERWRITE`, so re-running is safe but forces
    // SurrealDB to re-do all that DDL (meta tables + 2 events per user table) —
    // the dominant cost. Hash over the FINAL assembled bytes (post substitution,
    // post OVERWRITE injection, post per-table events) so any real change busts it.
    let hash = checksum_str(&internal_sql);
    if !force_schema_reapply()
        && read_stored_schema_hash(client, "internal").as_deref() == Some(&hash)
    {
        step.skip("unchanged");
        // Schedules still sync: their definitions live in sp00ky.yml, which
        // changes independently of the schema this hash covers.
        sync_schedules(client, config_path, &backend_processor);
        return Ok(());
    }

    // 5. Never rebuild an index that has not changed. The hash above covers the
    // assembled SQL; what runs is that SQL minus the index statements whose
    // live definition already matches (see prune_unchanged_index_defines).
    let (internal_sql, unchanged_indexes) = prune_unchanged_index_defines(client, &internal_sql);
    if unchanged_indexes > 0 {
        ui::detail(format!(
            "{} unchanged index(es) kept as-is (no rebuild)",
            unchanged_indexes
        ));
    }

    // 6. Execute against DB
    ui::detail(format!("executing {} KB of DDL", internal_sql.len() / 1024));
    step.set_message(format!(
        "applying · {} tables · {} events",
        table_count, event_count
    ));
    if let Err(e) = client.execute(&internal_sql) {
        step.fail("failed");
        return Err(e).context("Failed to apply internal Sp00ky schema");
    }

    // Record the applied hash only after a successful execute. The
    // _00_schema_state table is defined by the internal_sql we just ran, so it
    // exists by now.
    record_schema_hash(client, "internal", &hash);

    step.done(format!(
        "applied{}{} tables{}{} events",
        ui::glyphs().sep,
        table_count,
        ui::glyphs().sep,
        event_count
    ));
    sync_schedules(client, config_path, &backend_processor);
    Ok(())
}

/// Push declarative `schedules:` / `workflows:` into `_00_schedule`.
///
/// Deliberately non-fatal: a bad schedule definition must not fail a deploy that
/// otherwise succeeded, and the failure is loud enough to act on. `spky lint`
/// catches these before deploy, and `spky schedules sync` retries afterwards.
fn sync_schedules(
    client: &dyn MigrationDB,
    config_path: Option<&Path>,
    processor: &BackendProcessor,
) {
    let Some(config_path) = config_path.filter(|p| p.exists()) else { return };
    let base_dir = config_path.parent().unwrap_or(Path::new("."));
    let config = crate::backend::load_config(config_path);
    if config.schedules.is_empty() && config.workflows.is_empty() {
        // Still sweep: a schedule that was just deleted from the manifest has to
        // stop firing.
        match crate::schedule_sync::sync(client, &config, processor, base_dir) {
            Ok(report) if report.removed > 0 => {
                ui::step("Schedules").done(format!(
                    "removed {} no longer in sp00ky.yml",
                    report.removed
                ));
            }
            Ok(_) => {}
            Err(e) => ui::warn(format!("failed to sync schedules: {e:#}")),
        }
        return;
    }

    match crate::schedule_sync::sync(client, &config, processor, base_dir) {
        Ok(report) if report.is_noop() => {
            ui::detail(format!("schedules unchanged ({})", report.summary()));
        }
        Ok(report) => ui::step("Schedules").done(format!("synced: {}", report.summary())),
        Err(e) => ui::warn(format!("failed to sync schedules: {e:#}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::surreal_client::{AppliedMigration, MigrationDB, SurrealResponse};
    use std::cell::RefCell;
    use tempfile::TempDir;

    // ── Secret substitution ─────────────────────────────────────────────

    #[test]
    fn substitute_replaces_placeholders_with_and_without_spaces() {
        let secrets = vec![("JWT_PUBLIC_KEY".to_string(), "PUBPEM".to_string())];
        let out = substitute_secrets(
            "KEY '{{JWT_PUBLIC_KEY}}' ISSUER '{{ JWT_PUBLIC_KEY }}'",
            &secrets,
        )
        .unwrap();
        assert_eq!(out, "KEY 'PUBPEM' ISSUER 'PUBPEM'");
    }

    #[test]
    fn substitute_errors_on_unresolved_placeholder() {
        let err = substitute_secrets("KEY '{{JWT_PRIVATE_KEY}}'", &[]).unwrap_err();
        assert!(err.to_string().contains("JWT_PRIVATE_KEY"), "got: {err}");
    }

    #[test]
    fn substitute_noop_without_placeholders() {
        let src = "DEFINE TABLE user SCHEMAFULL;";
        assert_eq!(substitute_secrets(src, &[]).unwrap(), src);
    }

    #[test]
    fn substitute_ignores_non_placeholder_braces_and_keeps_utf8() {
        // lowercase / non-UPPER_SNAKE braces are not placeholders; box-drawing
        // chars in comments must survive byte-safe scanning.
        let src = "-- ─── note {{lower}} {{ not-a-key }} ───\nRETURN 1;";
        assert_eq!(substitute_secrets(src, &[]).unwrap(), src);
    }

    // ── Mock DB ─────────────────────────────────────────────────────────

    /// A mock MigrationDB that records calls and returns configurable results.
    struct MockDB {
        applied: RefCell<Vec<AppliedMigration>>,
        executed_queries: RefCell<Vec<String>>,
        recorded: RefCell<Vec<(String, String, String)>>,
        fail_execute: RefCell<bool>,
        // Hash returned for a `SELECT hash FROM _00_schema_state:<id>` query, to
        // exercise the schema-hash skip path. None => the row doesn't exist yet.
        stored_hash: RefCell<Option<String>>,
        // Live indexes per table, answered to `INFO FOR TABLE <t>;` as the
        // `indexes` map. A table not listed here answers with an ERR (as a
        // missing table does).
        live_indexes: RefCell<std::collections::HashMap<String, Vec<(String, String)>>>,
    }

    impl MockDB {
        fn new() -> Self {
            Self {
                applied: RefCell::new(vec![]),
                executed_queries: RefCell::new(vec![]),
                recorded: RefCell::new(vec![]),
                fail_execute: RefCell::new(false),
                stored_hash: RefCell::new(None),
                live_indexes: RefCell::new(Default::default()),
            }
        }

        fn set_live_indexes(&self, table: &str, indexes: &[(&str, &str)]) {
            self.live_indexes.borrow_mut().insert(
                table.to_string(),
                indexes
                    .iter()
                    .map(|(n, d)| (n.to_string(), d.to_string()))
                    .collect(),
            );
        }

        fn with_applied(migrations: Vec<AppliedMigration>) -> Self {
            let mock = Self::new();
            *mock.applied.borrow_mut() = migrations;
            mock
        }

        fn set_fail_execute(&self, fail: bool) {
            *self.fail_execute.borrow_mut() = fail;
        }

        fn set_stored_hash(&self, hash: &str) {
            *self.stored_hash.borrow_mut() = Some(hash.to_string());
        }

        /// Number of times the given SQL body was executed (excludes the hash
        /// SELECT/UPSERT bookkeeping queries).
        fn execute_count(&self, sql: &str) -> usize {
            self.executed_queries
                .borrow()
                .iter()
                .filter(|q| q.as_str() == sql)
                .count()
        }
    }

    impl MigrationDB for MockDB {
        fn ping(&self) -> Result<()> {
            Ok(())
        }

        fn ensure_ns_db(&self) -> Result<()> {
            Ok(())
        }

        fn ensure_migration_table(&self) -> Result<()> {
            Ok(())
        }

        fn execute(&self, query: &str) -> Result<Vec<SurrealResponse>> {
            if *self.fail_execute.borrow() {
                anyhow::bail!("Mock execute failure");
            }
            self.executed_queries.borrow_mut().push(query.to_string());
            // Answer the schema-hash read with the configured stored hash.
            if query.starts_with("SELECT hash FROM _00_schema_state") {
                let result = match self.stored_hash.borrow().as_ref() {
                    Some(h) => serde_json::json!([{ "hash": h }]),
                    None => serde_json::json!([]),
                };
                return Ok(vec![SurrealResponse {
                    status: "OK".to_string(),
                    result: Some(result),
                }]);
            }
            if let Some(table) = query
                .strip_prefix("INFO FOR TABLE ")
                .and_then(|q| q.strip_suffix(';'))
            {
                return Ok(vec![match self.live_indexes.borrow().get(table) {
                    Some(indexes) => SurrealResponse {
                        status: "OK".to_string(),
                        result: Some(serde_json::json!({
                            "indexes": indexes
                                .iter()
                                .map(|(n, d)| (n.clone(), serde_json::Value::String(d.clone())))
                                .collect::<serde_json::Map<String, serde_json::Value>>()
                        })),
                    },
                    None => SurrealResponse {
                        status: "ERR".to_string(),
                        result: None,
                    },
                }]);
            }
            Ok(vec![SurrealResponse {
                status: "OK".to_string(),
                result: None,
            }])
        }

        fn get_applied_migrations(&self) -> Result<Vec<AppliedMigration>> {
            Ok(self.applied.borrow().clone())
        }

        fn record_migration(&self, version: &str, name: &str, checksum: &str) -> Result<()> {
            self.recorded.borrow_mut().push((
                version.to_string(),
                name.to_string(),
                checksum.to_string(),
            ));
            Ok(())
        }

        fn update_migration_checksum(&self, _version: &str, _new_checksum: &str) -> Result<()> {
            Ok(())
        }
    }

    // ── Helpers ─────────────────────────────────────────────────────────

    /// Create a flat migration file in the migrations directory.
    fn create_migration_file(base: &Path, version: &str, name: &str, content: &str) -> PathBuf {
        fs::create_dir_all(base).unwrap();
        let file_path = base.join(format!("{}_{}.surql", version, name));
        fs::write(&file_path, content).unwrap();
        file_path
    }

    fn make_applied(version: &str, name: &str, chksum: &str) -> AppliedMigration {
        AppliedMigration {
            version: version.to_string(),
            name: name.to_string(),
            applied_at: "2024-01-01T12:00:00Z".to_string(),
            checksum: chksum.to_string(),
        }
    }

    // `checksum_str` is the crate helper (super::checksum_str), in scope via
    // `use super::*`.

    // ── schema-hash skip tests (apply_remote_functions_if_changed) ──────
    #[test]
    fn test_remote_fns_applies_when_no_stored_hash() {
        let mock = MockDB::new(); // stored_hash = None
        let sql = "DEFINE FUNCTION OVERWRITE fn::x() { RETURN 1; };";
        apply_remote_functions_if_changed(&mock, sql).unwrap();
        assert_eq!(mock.execute_count(sql), 1, "should apply when nothing stored");
        // hash recorded afterwards
        assert!(mock
            .executed_queries
            .borrow()
            .iter()
            .any(|q| q.contains("UPSERT _00_schema_state:remote_fns")));
    }

    #[test]
    fn test_remote_fns_skips_when_hash_matches() {
        let sql = "DEFINE FUNCTION OVERWRITE fn::x() { RETURN 1; };";
        let mock = MockDB::new();
        mock.set_stored_hash(&checksum_str(sql));
        apply_remote_functions_if_changed(&mock, sql).unwrap();
        assert_eq!(
            mock.execute_count(sql),
            0,
            "should skip the execute when the hash matches"
        );
    }

    #[test]
    fn test_remote_fns_applies_when_hash_differs() {
        let sql = "DEFINE FUNCTION OVERWRITE fn::x() { RETURN 2; };";
        let mock = MockDB::new();
        mock.set_stored_hash("deadbeef_stale_hash");
        apply_remote_functions_if_changed(&mock, sql).unwrap();
        assert_eq!(
            mock.execute_count(sql),
            1,
            "should re-apply when the stored hash differs"
        );
    }

    // ── sanitize_name tests ─────────────────────────────────────────────

    #[test]
    fn test_sanitize_name_simple() {
        assert_eq!(sanitize_name("initial"), "initial");
    }

    #[test]
    fn test_sanitize_name_spaces_to_underscores() {
        assert_eq!(sanitize_name("add user table"), "add_user_table");
    }

    #[test]
    fn test_sanitize_name_hyphens_to_underscores() {
        assert_eq!(sanitize_name("add-user-table"), "add_user_table");
    }

    #[test]
    fn test_sanitize_name_uppercase_to_lowercase() {
        assert_eq!(sanitize_name("AddUserTable"), "addusertable");
    }

    #[test]
    fn test_sanitize_name_strips_special_chars() {
        assert_eq!(sanitize_name("add@user#table!"), "addusertable");
    }

    #[test]
    fn test_sanitize_name_mixed_transforms() {
        assert_eq!(sanitize_name("Add User-Avatar v2!"), "add_user_avatar_v2");
    }

    #[test]
    fn test_sanitize_name_empty_string() {
        assert_eq!(sanitize_name(""), "");
    }

    #[test]
    fn test_sanitize_name_only_special_chars() {
        assert_eq!(sanitize_name("@#$%"), "");
    }

    // ── checksum tests ──────────────────────────────────────────────────

    #[test]
    fn test_checksum_consistent() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("test.surql");
        fs::write(&path, "DEFINE TABLE test;").unwrap();

        let hash1 = checksum(&path).unwrap();
        let hash2 = checksum(&path).unwrap();
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_checksum_different_content_differs() {
        let dir = TempDir::new().unwrap();
        let path1 = dir.path().join("a.surql");
        let path2 = dir.path().join("b.surql");
        fs::write(&path1, "DEFINE TABLE a;").unwrap();
        fs::write(&path2, "DEFINE TABLE b;").unwrap();

        assert_ne!(checksum(&path1).unwrap(), checksum(&path2).unwrap());
    }

    #[test]
    fn test_checksum_missing_file_errors() {
        let result = checksum(Path::new("/nonexistent/file.surql"));
        assert!(result.is_err());
    }

    #[test]
    fn test_checksum_is_valid_hex_sha256() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("test.surql");
        fs::write(&path, "content").unwrap();

        let hash = checksum(&path).unwrap();
        // SHA-256 hex output is 64 chars
        assert_eq!(hash.len(), 64);
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    // ── scan_migrations tests ───────────────────────────────────────────

    #[test]
    fn test_scan_nonexistent_dir_returns_empty() {
        let result = scan_migrations(Path::new("/nonexistent/migrations")).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_scan_empty_dir_returns_empty() {
        let dir = TempDir::new().unwrap();
        let result = scan_migrations(dir.path()).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_scan_finds_valid_migration() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "initial", "-- up");

        let result = scan_migrations(dir.path()).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].version, "20240101120000");
        assert_eq!(result[0].name, "initial");
    }

    #[test]
    fn test_scan_sorts_by_version() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240103120000", "third", "-- up");
        create_migration_file(dir.path(), "20240101120000", "first", "-- up");
        create_migration_file(dir.path(), "20240102120000", "second", "-- up");

        let result = scan_migrations(dir.path()).unwrap();
        assert_eq!(result.len(), 3);
        assert_eq!(result[0].version, "20240101120000");
        assert_eq!(result[1].version, "20240102120000");
        assert_eq!(result[2].version, "20240103120000");
    }

    #[test]
    fn test_scan_skips_directories() {
        let dir = TempDir::new().unwrap();
        fs::create_dir_all(dir.path().join("20240101120000_not_a_file")).unwrap();
        create_migration_file(dir.path(), "20240101120000", "real", "-- up");

        let result = scan_migrations(dir.path()).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].name, "real");
    }

    #[test]
    fn test_scan_skips_non_surql_files() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("20240101120000_readme.txt"), "text").unwrap();
        create_migration_file(dir.path(), "20240101120000", "real", "-- up");

        let result = scan_migrations(dir.path()).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].name, "real");
    }

    #[test]
    fn test_scan_skips_files_without_underscore() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("nounderscore.surql"), "-- sql").unwrap();

        let result = scan_migrations(dir.path()).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_scan_skips_files_with_short_version() {
        let dir = TempDir::new().unwrap();
        // Version must be exactly 14 digits
        fs::write(dir.path().join("2024_too_short.surql"), "-- sql").unwrap();
        fs::write(dir.path().join("12345_short.surql"), "-- sql").unwrap();

        let result = scan_migrations(dir.path()).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_scan_skips_files_with_non_digit_version() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("2024010112000a_bad_ver.surql"), "-- sql").unwrap();

        let result = scan_migrations(dir.path()).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_scan_sets_correct_path() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "test", "-- up");

        let result = scan_migrations(dir.path()).unwrap();
        assert_eq!(result[0].path, dir.path().join("20240101120000_test.surql"));
    }

    #[test]
    fn test_scan_handles_multi_underscore_names() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "add_user_table", "-- up");

        let result = scan_migrations(dir.path()).unwrap();
        assert_eq!(result.len(), 1);
        // The name should be everything after the first underscore
        assert_eq!(result[0].name, "add_user_table");
    }

    // ── create tests ────────────────────────────────────────────────────

    #[test]
    fn test_create_makes_file() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        create(&migrations_dir, "initial", None, None, None).unwrap();

        let entries: Vec<_> = fs::read_dir(&migrations_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .collect();
        assert_eq!(entries.len(), 1);

        let path = entries[0].path();
        assert!(path.extension().unwrap() == "surql");
        assert!(path.is_file());
    }

    #[test]
    fn test_create_uses_timestamp_name_pattern() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        create(&migrations_dir, "add_users", None, None, None).unwrap();

        let entry = fs::read_dir(&migrations_dir)
            .unwrap()
            .next()
            .unwrap()
            .unwrap();
        let name = entry.file_name().to_string_lossy().to_string();

        // Format: {14-digit timestamp}_{sanitized_name}.surql
        assert!(name.ends_with("_add_users.surql"));
        let version = &name[..14];
        assert!(version.chars().all(|c| c.is_ascii_digit()));
        assert_eq!(version.len(), 14);
    }

    #[test]
    fn test_create_sanitizes_name() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        create(&migrations_dir, "Add User-Avatar!", None, None, None).unwrap();

        let entry = fs::read_dir(&migrations_dir)
            .unwrap()
            .next()
            .unwrap()
            .unwrap();
        let name = entry.file_name().to_string_lossy().to_string();
        assert!(name.ends_with("_add_user_avatar.surql"));
    }

    #[test]
    fn test_create_has_header_comment() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        create(&migrations_dir, "test", None, None, None).unwrap();

        let entry = fs::read_dir(&migrations_dir)
            .unwrap()
            .next()
            .unwrap()
            .unwrap();
        let content = fs::read_to_string(entry.path()).unwrap();
        assert!(content.starts_with("-- Migration: test"));
        assert!(content.contains("-- Created:"));
        assert!(content.contains("Write your forward migration"));
    }

    #[test]
    fn test_create_with_schema_prepopulates() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        // Create a schema file
        let schema_path = dir.path().join("schema.surql");
        fs::write(&schema_path, "DEFINE TABLE user SCHEMAFULL;").unwrap();

        create(&migrations_dir, "initial", Some(&schema_path), None, None).unwrap();

        let entry = fs::read_dir(&migrations_dir)
            .unwrap()
            .next()
            .unwrap()
            .unwrap();
        let content = fs::read_to_string(entry.path()).unwrap();
        assert!(content.contains("DEFINE TABLE user SCHEMAFULL;"));
        assert!(content.contains("WARNING"));
        assert!(content.contains("ONLY the incremental changes"));
    }

    #[test]
    fn test_create_with_nonexistent_schema_errors() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        let result = create(
            &migrations_dir,
            "test",
            Some(Path::new("/nonexistent/schema.surql")),
            None,
            None,
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_create_multiple_migrations_are_unique() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        create(&migrations_dir, "first", None, None, None).unwrap();
        // Sleep a tiny bit so timestamp differs (or they'll collide)
        std::thread::sleep(std::time::Duration::from_millis(1100));
        create(&migrations_dir, "second", None, None, None).unwrap();

        let entries: Vec<_> = fs::read_dir(&migrations_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .collect();
        assert_eq!(entries.len(), 2);
    }

    #[test]
    fn test_create_creates_parent_dirs() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("deep/nested/migrations");

        create(&migrations_dir, "test", None, None, None).unwrap();
        assert!(migrations_dir.exists());
    }

    // ── apply tests ─────────────────────────────────────────────────────

    #[test]
    fn test_apply_no_pending_migrations() {
        let dir = TempDir::new().unwrap();
        let mock = MockDB::new();

        // Empty dir = no migrations
        apply(&mock, dir.path()).unwrap();
        assert!(mock.recorded.borrow().is_empty());
    }

    #[test]
    fn test_apply_applies_single_pending_migration() {
        let dir = TempDir::new().unwrap();
        let up_sql = "DEFINE TABLE user SCHEMAFULL;";
        create_migration_file(dir.path(), "20240101120000", "initial", up_sql);

        let mock = MockDB::new();
        apply(&mock, dir.path()).unwrap();

        let recorded = mock.recorded.borrow();
        assert_eq!(recorded.len(), 1);
        assert_eq!(recorded[0].0, "20240101120000");
        assert_eq!(recorded[0].1, "initial");
        assert_eq!(recorded[0].2, checksum_str(up_sql));
    }

    #[test]
    fn test_apply_applies_multiple_in_order() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "first", "CREATE first;");
        create_migration_file(dir.path(), "20240102120000", "second", "CREATE second;");
        create_migration_file(dir.path(), "20240103120000", "third", "CREATE third;");

        let mock = MockDB::new();
        apply(&mock, dir.path()).unwrap();

        let recorded = mock.recorded.borrow();
        assert_eq!(recorded.len(), 3);
        assert_eq!(recorded[0].0, "20240101120000");
        assert_eq!(recorded[1].0, "20240102120000");
        assert_eq!(recorded[2].0, "20240103120000");

        // Verify the SQL was actually executed (wrapped in transactions)
        let queries = mock.executed_queries.borrow();
        assert_eq!(queries.len(), 3);
        assert_eq!(
            queries[0],
            "BEGIN TRANSACTION;\nCREATE first;\nCOMMIT TRANSACTION;"
        );
        assert_eq!(
            queries[1],
            "BEGIN TRANSACTION;\nCREATE second;\nCOMMIT TRANSACTION;"
        );
        assert_eq!(
            queries[2],
            "BEGIN TRANSACTION;\nCREATE third;\nCOMMIT TRANSACTION;"
        );
    }

    #[test]
    fn test_apply_skips_already_applied() {
        let dir = TempDir::new().unwrap();
        let up_sql = "CREATE first;";
        create_migration_file(dir.path(), "20240101120000", "first", up_sql);
        create_migration_file(dir.path(), "20240102120000", "second", "CREATE second;");

        // Mark first as already applied
        let mock = MockDB::with_applied(vec![make_applied(
            "20240101120000",
            "first",
            &checksum_str(up_sql),
        )]);

        apply(&mock, dir.path()).unwrap();

        let recorded = mock.recorded.borrow();
        assert_eq!(recorded.len(), 1);
        assert_eq!(recorded[0].0, "20240102120000");
    }

    #[test]
    fn test_apply_checksum_mismatch_aborts() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "initial", "MODIFIED content");

        // Applied migration has a different checksum (original content was different)
        let mock = MockDB::with_applied(vec![make_applied(
            "20240101120000",
            "initial",
            "original_checksum_that_doesnt_match",
        )]);

        let result = apply(&mock, dir.path());
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("Checksum mismatch"));
    }

    #[test]
    fn test_apply_execute_failure_aborts() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "initial", "INVALID SQL;");

        let mock = MockDB::new();
        mock.set_fail_execute(true);

        let result = apply(&mock, dir.path());
        assert!(result.is_err());
        // No migration should have been recorded
        assert!(mock.recorded.borrow().is_empty());
    }

    #[test]
    fn test_apply_all_already_applied() {
        let dir = TempDir::new().unwrap();
        let up_sql = "CREATE stuff;";
        create_migration_file(dir.path(), "20240101120000", "initial", up_sql);

        let mock = MockDB::with_applied(vec![make_applied(
            "20240101120000",
            "initial",
            &checksum_str(up_sql),
        )]);

        apply(&mock, dir.path()).unwrap();
        assert!(mock.recorded.borrow().is_empty());
    }

    // ── Integration-style tests (filesystem + mock DB) ──────────────────

    #[test]
    fn test_full_lifecycle_create_then_apply() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        // Step 1: Create a migration
        create(&migrations_dir, "add_users", None, None, None).unwrap();

        // Write actual SQL to the created migration
        let entries: Vec<_> = fs::read_dir(&migrations_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .collect();
        assert_eq!(entries.len(), 1);

        let mig_path = entries[0].path();
        let up_sql = "DEFINE TABLE user SCHEMAFULL;\nDEFINE FIELD name ON user TYPE string;";
        fs::write(&mig_path, up_sql).unwrap();

        // Step 2: Apply
        let mock = MockDB::new();
        apply(&mock, &migrations_dir).unwrap();

        let recorded = mock.recorded.borrow();
        assert_eq!(recorded.len(), 1);
        assert_eq!(recorded[0].1, "add_users");

        let queries = mock.executed_queries.borrow();
        assert_eq!(
            queries[0],
            format!("BEGIN TRANSACTION;\n{}\nCOMMIT TRANSACTION;", up_sql)
        );
        drop(recorded);
        drop(queries);

        // Step 3: Re-apply should be no-op (all applied)
        let version = {
            let r = mock.recorded.borrow();
            r[0].0.clone()
        };
        let chk = {
            let r = mock.recorded.borrow();
            r[0].2.clone()
        };
        let mock2 = MockDB::with_applied(vec![make_applied(&version, "add_users", &chk)]);

        apply(&mock2, &migrations_dir).unwrap();
        assert!(mock2.recorded.borrow().is_empty());
    }

    #[test]
    fn test_apply_then_create_new_then_apply_again() {
        let dir = TempDir::new().unwrap();
        let migrations_dir = dir.path().join("migrations");

        // First migration
        let up1 = "DEFINE TABLE user SCHEMAFULL;";
        create_migration_file(&migrations_dir, "20240101120000", "initial", up1);

        // Apply first
        let mock = MockDB::new();
        apply(&mock, &migrations_dir).unwrap();
        assert_eq!(mock.recorded.borrow().len(), 1);

        // Add second migration
        let up2 = "DEFINE FIELD avatar ON user TYPE string;";
        create_migration_file(&migrations_dir, "20240102120000", "add_avatar", up2);

        // Apply again with first already applied
        let mock2 = MockDB::with_applied(vec![make_applied(
            "20240101120000",
            "initial",
            &checksum_str(up1),
        )]);
        apply(&mock2, &migrations_dir).unwrap();

        let recorded = mock2.recorded.borrow();
        assert_eq!(recorded.len(), 1);
        assert_eq!(recorded[0].0, "20240102120000");
        assert_eq!(recorded[0].1, "add_avatar");
    }

    // ── validate_applied_checksums tests ─────────────────────────────

    #[test]
    fn test_validate_checksums_all_match() {
        let dir = TempDir::new().unwrap();
        let content = "DEFINE TABLE user SCHEMAFULL;";
        create_migration_file(dir.path(), "20240101120000", "initial", content);

        let filesystem = scan_migrations(dir.path()).unwrap();
        let applied = vec![make_applied(
            "20240101120000",
            "initial",
            &checksum_str(content),
        )];

        let warnings = validate_applied_checksums(&applied, &filesystem).unwrap();
        assert!(warnings.is_empty());
    }

    #[test]
    fn test_validate_checksums_mismatch_errors() {
        let dir = TempDir::new().unwrap();
        create_migration_file(dir.path(), "20240101120000", "initial", "MODIFIED content");

        let filesystem = scan_migrations(dir.path()).unwrap();
        let applied = vec![make_applied(
            "20240101120000",
            "initial",
            "original_checksum_that_doesnt_match",
        )];

        let result = validate_applied_checksums(&applied, &filesystem);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("Checksum mismatch"));
    }

    #[test]
    fn test_validate_checksums_missing_file_warns() {
        let dir = TempDir::new().unwrap();
        // Don't create any files on disk
        let filesystem = scan_migrations(dir.path()).unwrap();
        let applied = vec![make_applied("20240101120000", "initial", "some_checksum")];

        let warnings = validate_applied_checksums(&applied, &filesystem).unwrap();
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("not found on disk"));
    }

    // ── Unchanged-index pruning ─────────────────────────────────────────

    #[test]
    fn normalize_index_define_matches_info_for_table_output() {
        let ours = "DEFINE INDEX OVERWRITE idx_srun_active ON TABLE _00_schedule_run\n    COLUMNS schedule_name, key, status;";
        let live = "DEFINE INDEX idx_srun_active ON _00_schedule_run FIELDS schedule_name, key, status";
        assert_eq!(normalize_index_define(ours), normalize_index_define(live));

        let unique_ours =
            "DEFINE INDEX OVERWRITE idx_record_id ON TABLE _00_version COLUMNS record_id UNIQUE;";
        let unique_live = "DEFINE INDEX idx_record_id ON _00_version FIELDS record_id UNIQUE";
        assert_eq!(normalize_index_define(unique_ours), normalize_index_define(unique_live));
        assert_eq!(
            normalize_index_define("DEFINE INDEX IF NOT EXISTS a ON TABLE t COLUMNS x,y;"),
            normalize_index_define("DEFINE INDEX a ON t FIELDS x, y")
        );
        // A real definition change still reads as a change.
        assert_ne!(
            normalize_index_define(unique_ours),
            normalize_index_define("DEFINE INDEX idx_record_id ON _00_version FIELDS record_id")
        );
    }

    #[test]
    fn index_define_target_parses_the_forms_we_emit() {
        assert_eq!(
            index_define_target("DEFINE INDEX OVERWRITE idx ON TABLE t COLUMNS a;"),
            Some(("idx".to_string(), "t".to_string()))
        );
        assert_eq!(
            index_define_target("DEFINE INDEX IF NOT EXISTS idx ON t FIELDS a;"),
            Some(("idx".to_string(), "t".to_string()))
        );
        assert_eq!(index_define_target("DEFINE TABLE t;"), None);
    }

    #[test]
    fn prune_drops_only_indexes_whose_live_definition_matches() {
        let db = MockDB::new();
        db.set_live_indexes(
            "_00_version",
            &[("idx_record_id", "DEFINE INDEX idx_record_id ON _00_version FIELDS record_id UNIQUE")],
        );
        // Live definition differs (no UNIQUE): must be re-defined.
        db.set_live_indexes(
            "_00_admin",
            &[("idx_admin_user", "DEFINE INDEX idx_admin_user ON _00_admin FIELDS user")],
        );
        let sql = "DEFINE TABLE OVERWRITE _00_version SCHEMALESS;\n\
                   -- DEFINE INDEX OVERWRITE commented ON TABLE _00_version COLUMNS x;\n\
                   DEFINE INDEX OVERWRITE idx_record_id ON TABLE _00_version COLUMNS record_id UNIQUE;\n\
                   DEFINE INDEX OVERWRITE idx_admin_user ON TABLE _00_admin COLUMNS user UNIQUE;\n\
                   DEFINE INDEX OVERWRITE idx_new ON TABLE _00_feature_flag COLUMNS key UNIQUE;\n\
                   DEFINE EVENT OVERWRITE e ON TABLE _00_version WHEN true THEN { RETURN 1; };";

        let (out, pruned) = prune_unchanged_index_defines(&db, sql);
        assert_eq!(pruned, 1);
        assert!(
            !out.contains("DEFINE INDEX OVERWRITE idx_record_id"),
            "an unchanged index must not be re-defined (that rebuilds it):\n{out}"
        );
        assert!(out.contains("-- index idx_record_id on _00_version unchanged; not rebuilt"));
        assert!(
            out.contains("DEFINE INDEX OVERWRITE idx_admin_user ON TABLE _00_admin COLUMNS user UNIQUE;"),
            "a changed definition keeps its OVERWRITE:\n{out}"
        );
        assert!(
            out.contains("DEFINE INDEX OVERWRITE idx_new ON TABLE _00_feature_flag COLUMNS key UNIQUE;"),
            "an index missing from a live table (or a missing table) keeps its OVERWRITE:\n{out}"
        );
        assert!(out.contains("-- DEFINE INDEX OVERWRITE commented ON TABLE _00_version COLUMNS x;"));
        assert!(out.contains("DEFINE TABLE OVERWRITE _00_version SCHEMALESS;"));
        assert!(out.contains("DEFINE EVENT OVERWRITE e ON TABLE _00_version WHEN true THEN { RETURN 1; };"));
        // One INFO per table, not per statement.
        let infos = db
            .executed_queries
            .borrow()
            .iter()
            .filter(|q| q.starts_with("INFO FOR TABLE _00_version"))
            .count();
        assert_eq!(infos, 1);

        // Nothing readable about the live schema: every statement stays.
        let (out2, pruned2) = prune_unchanged_index_defines(&MockDB::new(), sql);
        assert_eq!(pruned2, 0);
        assert!(out2.contains(
            "DEFINE INDEX OVERWRITE idx_record_id ON TABLE _00_version COLUMNS record_id UNIQUE;"
        ));
    }
}
